### ISSUE TITLE
default value for update Mutation

### ISSUE THREAD

**Issue by bingzheaaa** [graphile/postgraphile#916] opened 2018-11-21 13:30 UTC
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version:4.0.1

could i set a default value for update Mutation args.
like:
mutation {
  	updateUserById(input: {userPatch:{name:"test"}, id:1}){
              user{id name updatetime}
       }
}

return field updatetime will be set currenttime.

**Comment by benjie** [comment] 2018-11-21 13:50
You can write a plugin that will do this; however I would advise against it. Instead I would use database triggers to achieve this goal, e.g.

https://github.com/graphile/bootstrap-react-apollo/blob/c4eb266f66a5287a535f57941ae1bce188035750/db/migrations/20181102_191809.app_private.functions.tg__timestamps.create-up.sql

https://github.com/graphile/bootstrap-react-apollo/blob/c4eb266f66a5287a535f57941ae1bce188035750/db/migrations/20181102_193100.app_public.tables.users-up.sql#L38-L41

e.g.

```sql
create function app_private.tg__timestamps() returns trigger as $$
begin
  NEW.created_at = (case when TG_OP = 'INSERT' then NOW() else OLD.created_at end);
  NEW.updated_at = (case when TG_OP = 'UPDATE' and OLD.updated_at <= NOW() then OLD.updated_at + interval '1 millisecond' else NOW() end);
  return NEW;
end;
$$ language plpgsql volatile set search_path from current;

create trigger _100_timestamps after insert or update on app_public.users
  for each row execute procedure app_private.tg__timestamps();

create trigger _100_timestamps after insert or update on app_public.forums
  for each row execute procedure app_private.tg__timestamps();

create trigger _100_timestamps after insert or update on app_public.posts
  for each row execute procedure app_private.tg__timestamps();
```

If you're interested in writing a plugin to do this, let me know and I can advise.

**Comment by benjie** [comment] 2018-11-21 13:51
[semi-automated message] Thanks for your question; hopefully we're well on the way to helping you solve your issue. This doesn't currently seem to be a bug in the library so I'm going to close the issue, but please feel free to keep requesting help below and if it does turn out to be a bug we can definitely re-open it 👍

**Closed by benjie** 2018-11-21 13:51 UTC
Labels: ❔ question

**Comment by bingzheaaa** [comment] 2018-11-21 13:58
First of all, thank you for your reply.
could you tell me how to  write a plugin?

**Comment by benjie** [comment] 2018-11-21 15:00
Sure; there's some documentation here: https://www.graphile.org/postgraphile/extending-raw/

I've also written a plugin that achieves close to your specific goal here:

https://github.com/graphile/graphile.github.io/blob/4e181a135ae23e8b6ed50abaf2f0a62bac337632/examples/plugins/0300_mutation_wrappers/OverrideArgValuePlugin.js

A more conventional plugin for setting a default would be this one (but the problem is it adds the default to GraphQL, which means it cannot be dynamic as you desire):

https://github.com/graphile/graphile.github.io/blob/4e181a135ae23e8b6ed50abaf2f0a62bac337632/examples/plugins/0200_types/SetInputObjectDefaultValue.js

Writing plugins that wrap resolvers is going to be a LOT easier soon; I'm planning to write a helper for it 👍

**Comment by bingzheaaa** [comment] 2018-11-22 02:12
thanks!

**Comment by benjie** [comment] 2018-11-22 18:01
4.1.0 will have a new `makeWrapResolversPlugin` you can use to more easily wrap resolvers; see some examples in the PR:

https://github.com/graphile/graphile-engine/pull/352
