### ISSUE TITLE
Supporting column level access privilege grants

### ISSUE THREAD

**Issue by bendiy** [graphile/postgraphile#151] opened 2016-10-12 17:30 UTC
I'm curious if it would be possible to support column level access privilege grants.

If you have a schema like this:

```
CREATE TABLE item (
  id               serial not null primary key,
  name             integer not null,
  price            integer not null,
  cost             integer not null, -- Only the manager role can see the cost
  created_at       timestamp,        -- Only the manager role can see created_at
  updated_at       timestamp
);

GRANT SELECT (
  id,
  name,
  price
) ON item TO anonymous;

GRANT SELECT (
  id,
  name,
  price,
  updated_at
) ON item TO cashier;

GRANT ALL ON item TO manager;
```

Based on the `role`, you can introspect what that role can see:

```
-- Introspection:
SELECT
  column_name
FROM information_schema.column_privileges
WHERE table_catalog = current_database()
  AND table_schema = 'public'
  AND table_name = 'item'
  AND grantee = 'anonymous'
  AND privilege_type = 'SELECT';
```

The `anonymous` and `cashier` roles cannot do a `SELECT * FROM item;`, but the `manager` role can. Based on the introspection, you can build up and expose a query the role is allowed to make.

If I apply column access restrictions like this to my schema, how will that affect PostGraphQL?

**Comment by calebmer** [comment] 2016-10-13 01:31
Yep, so the way PostGraphQL currently selects columns is basically by using `select *`. Of course this is sub-optimal as we could be selecting less information, and we end up running into permission problems such as this.

How important is this feature to you? It isn’t trivial to fix, but is definitely on my priority list. The PostGraphQL website needs to come first though. Currently that may mean I get to this in 1 to 2 months. Let me know if you are interested in contributing to the project so we can knock things off the stack faster :+1:

**Comment by bendiy** [comment] 2016-10-13 13:55
I'm considering using column level grants in another project and have been looking into how PostGraphQL and PostgREST handle privileges. We currently us an ORM layer, but I'd like to push as much to the database schema as possible. I'd like to have a schema that's still compatible with PostGraphQL and PostgREST. In my initial testing, I've found the performance of `information_schema.column_privileges` queries to be very poor. Adding close to 100ms. I can get that to sub 10ms by caching it into a Materialized View, but that requires a refresh on any schema change.

Where does PostGraphQL make/cache it's introspection? @calebmer mentioned in another issue that he's trying to do the introspection in one query in v2.0, but it was linked to and moved a few times now. Currently 404s.

**Comment by calebmer** [comment] 2016-10-13 16:27
Here is the introspection query: https://github.com/calebmer/postgraphql/blob/24b78407bb6fba6732665816f9016073800443e0/resources/introspection-query.sql (should be a permalink)

We don't query `introspection_schema` at all. It is just a bunch of views with data that is very hard to work with from a technical perspective. Instead we use the canonical `pg_catalog` schema, which while it may be harder to work, provides a much better view of schema data. We can look at the implementation of `information_schema.column_privileges` (which likely uses `pg_catalog` internally).

If you need anymore information, let me know 👍

**Comment by bendiy** [comment] 2016-10-13 20:44
I extracted the query from the `information_schema.column_privileges` view and simplified it. This runs in under 5ms.
```sql
SELECT
  nspname, -- Schema
  relname, -- Table
  attname, -- Column role is allowed to select on.
  grantee.rolname,
  privilege_type, -- Action type ('INSERT', 'SELECT', 'UPDATE', 'REFERENCES', etc.)
  is_grantable
FROM (
  -- Table level grants:
  SELECT 
    pg_namespace.nspname,
    pg_class.relname,
    pg_attribute.attname,
    (aclexplode(COALESCE(pg_class.relacl, acldefault('r'::"char", pg_class.relowner)))).grantor AS grantor,
    (aclexplode(COALESCE(pg_class.relacl, acldefault('r'::"char", pg_class.relowner)))).grantee AS grantee,
    (aclexplode(COALESCE(pg_class.relacl, acldefault('r'::"char", pg_class.relowner)))).privilege_type AS privilege_type,
    (aclexplode(COALESCE(pg_class.relacl, acldefault('r'::"char", pg_class.relowner)))).is_grantable AS is_grantable
  FROM pg_class
  JOIN pg_attribute ON pg_class.oid = pg_attribute.attrelid
  JOIN pg_namespace ON pg_class.relnamespace = pg_namespace.oid
  WHERE true
    AND pg_attribute.attnum > 0
    AND NOT pg_attribute.attisdropped
    AND pg_class.relkind = ANY (ARRAY['r'::"char", 'v'::"char", 'f'::"char"])
    
  UNION
  -- Column level grants:
  SELECT 
    pg_namespace.nspname,
    pg_class.relname,
    pg_attribute.attname,
    (aclexplode(COALESCE(pg_attribute.attacl, acldefault('c'::"char", pg_class.relowner)))).grantor AS grantor,
    (aclexplode(COALESCE(pg_attribute.attacl, acldefault('c'::"char", pg_class.relowner)))).grantee AS grantee,
    (aclexplode(COALESCE(pg_attribute.attacl, acldefault('c'::"char", pg_class.relowner)))).privilege_type AS privilege_type,
    (aclexplode(COALESCE(pg_attribute.attacl, acldefault('c'::"char", pg_class.relowner)))).is_grantable AS is_grantable
  FROM pg_attribute
  JOIN pg_class ON pg_attribute.attrelid = pg_class.oid
  JOIN pg_namespace ON pg_class.relnamespace = pg_namespace.oid
  WHERE true
    AND pg_attribute.attnum > 0 
    AND NOT pg_attribute.attisdropped
    AND pg_class.relkind = ANY (ARRAY['r'::"char", 'v'::"char", 'f'::"char"])
) AS grants
JOIN (
  SELECT 
    pg_authid.oid,
    pg_authid.rolname
  FROM pg_authid
  
  UNION ALL
  SELECT 0::oid AS oid,
    'PUBLIC'::name
) grantee ON grants.grantee = grantee.oid
WHERE true
  AND (pg_has_role(grantee.oid, 'USAGE'::text) OR grantee.rolname = 'PUBLIC'::name)
  AND privilege_type = 'SELECT'
  AND nspname = 'the-schema-here'
  AND relname = 'the-table-here'
  AND grantee.rolname = 'my-role-here'
;
```

**Comment by bendiy** [comment] 2016-10-13 20:55
This works pretty well too depending on what you need.
```sql
SELECT 
  pg_namespace.nspname,
  pg_class.relname,
  pg_attribute.attname
FROM pg_class
JOIN pg_attribute ON pg_class.oid = pg_attribute.attrelid
JOIN pg_namespace ON pg_class.relnamespace = pg_namespace.oid
WHERE true
  AND pg_class.relkind = ANY (ARRAY['r'::"char", 'v'::"char", 'f'::"char"])
  AND nspname = 'the-schema-here'
  AND relname = 'the-table-here'
  AND has_column_privilege('my-role-here', pg_namespace.nspname || '.' || pg_class.relname, pg_attribute.attname, 'SELECT');
```

**Comment by JesperWe** [comment] 2016-11-19 19:44
I'm just getting started evaluating your tool (which I think as a concept is pure genius!), but I immediately ran into this. In a real life application there will be many cases where a role should have access only to some properties of an object. 

I might be naive, but why do you need the introspection in this case? Isn't it the `select *` that is the problem? If you instead did select the columns corresponding to the nodes in the graphql query, the query would work if the role had access, and fail if it didn't, which for me is the expected behaviour.

**Comment by bendiy** [comment] 2016-11-21 15:44
I think there's two approaches to this.

1. The equivalent of a `SELECT *` where you ask for a resource and get all the columns/properties it has
2. The one @JesperWe suggests where the user is submitting a query for only columns they can view.

If a user asks for a full resource, but they are not able to view some of the columns, we either throw an error, or use introspection to give them only the columns they can access.
The introspection can also support the auto complete feature in the GraphiQL IDE. The connected user would only get auto complete prompts for columns/properties they can view.

**Comment by bendiy** [comment] 2016-11-21 17:47
Also, based on http://graphql.org/learn/introspection/, what should a user get with limited column access when running:
```
{
  __schema {
    types {
      name
    }
  }
}
```
All columns/properties or only those they have access to? 
Can the properties they don't have access to be annotated in some way in the schema response?

**Comment by JesperWe** [comment] 2016-11-21 18:35
I understand that the introspection is needed for autocomplete and a 100% correct schema. But since it seems (according to the above discussion) to be a larger task, I proposed the more pragmatic (and hopefully less burdensome) approach. 

Because for me, the current table level permissions don't cut it for production deployment. Take for example the accounts table: Any logged in user having access to all registered account contact details does not seem like a good idea. 

Can be worked around by splitting the account in a public and private table, but then the GraphQL schema also has two parts, which is not nice. And the same would probably apply to many other entities in most peoples datamodels.

**Comment by calebmer** [comment] 2016-11-23 21:00
In order to work on this I’m going to need some money to take a week or so off work and implement support for this. I agree that this is a use-case we should definitely support. If anyone can fund the project for a week, or submit a PR send me a DM on Gitter or an email (public on my GitHub profile) and we can move forward :+1:

**Comment by bendiy** [comment] 2016-11-30 17:13
@calebmer 
> In order to work on this I’m going to need some money to take a week or so off work and implement support for this.

That's a totally reasonable position. I can't make that commitment yet. Not using this in production. I'm still designing my schema/API. It would be _nice_ to have PostGraphQL work with it out of the box. I'll circle back to this when I'm ready. Time permitting, I'd be happy to submit a PR for this feature if I can get to it. No time estimate on that. I know it won't be _soon_.

**Comment by benjie** [comment] 2017-07-09 21:41
This is either fixed by v4 or possible via a plugin to v4; at the moment I'd recommend using different instances/schemas for different database roles: 

https://github.com/postgraphql/postgraphql/issues/427

**Comment by benjie** [comment] 2017-11-29 20:16
I'm going to declare this as fixed in V4; but beware that the un-granted columns are still available to query (just doing so will cause an error) and that I don't know what effect computed columns may have on this.

**Comment by benjie** [comment] 2018-06-24 08:42
https://stackoverflow.com/a/23461690/141284

**Comment by benjie** [comment] 2018-06-24 08:45
Since we support this now, and you can use smart comments to emulate the permissions detection, I'm going to close it. Would be nice to have this auto-detected but as Caleb notes it's a significant undertaking. If someone wants to sponsor this please get in touch!

**Closed by benjie** 2018-06-24 08:45 UTC
Labels: Fixed in v4, bug
