### ISSUE TITLE
Type naming conflict error

### ISSUE THREAD

**Issue by mzagaja** [graphile/postgraphile#1170] opened 2019-10-28 18:38 UTC
* [x] bug report

PostGraphile version:

4.4.4

Minimal SQL file that can be loaded into a clean database:

https://github.com/hasura/graphql-engine/files/3741139/hasura-schema.sql.zip

Steps to reproduce:

`docker run --init -p 8080:8080 graphile/postgraphile -c postgres://XXX -p 8080 -s tabular --enhance-graphiql --dynamic-json`

Current behavior:

Expected behavior:
When opening GraphiQL endpoint I get the following error output:

```
A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

Error: A type naming conflict has occurred - two entities have tried to define the same type 'MapcLeadCommercialsOrderBy'.

  The first entity was:

    Adding connection "orderBy" argument for table "tabular"."mapc-lead-commercial". You can rename the table's GraphQL type via a 'Smart Comment':

      COMMENT ON TABLE "tabular"."mapc-lead-commercial" IS E'@name newNameHere';

  The second entity was:

    Adding connection "orderBy" argument for table "tabular"."mapc_lead_commercial". You can rename the table's GraphQL type via a 'Smart Comment':

      COMMENT ON TABLE "tabular"."mapc_lead_commercial" IS E'@name newNameHere';
    at Object.addType (/postgraphile/node_modules/graphile-build/node8plus/makeNewBuild.js:253:17)
    at Object.newWithHooks (/postgraphile/node_modules/graphile-build/node8plus/makeNewBuild.js:659:14)
    at /postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgConnectionArgOrderBy.js:34:7
    at Array.forEach (<anonymous>)
    at /postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgConnectionArgOrderBy.js:27:38
    at SchemaBuilder.applyHooks (/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:252:20)
    at SchemaBuilder.createBuild (/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:313:10)
    at SchemaBuilder.buildSchema (/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:321:26)
    at Object.exports.createPostGraphileSchema (/postgraphile/node_modules/postgraphile-core/node8plus/index.js:225:28)
    at runMicrotasks (<anonymous>)
```

I ran the following SQL to do smart comments as suggested:

```SQL
-- 2019-10-28 14:11:04.4320
COMMENT ON TABLE "tabular"."mapc-lead-commercial" IS E'@name mapcLeadCommercial2';
```

However the error persists after reloading Postgraphile. The table definition is now:

```SQL
-- This script only contains the table creation statements and does not fully represent the table in the database. It's still missing: indices, triggers. Do not use it as a backup.

-- Table Definition
CREATE TABLE "tabular"."mapc-lead-commercial" (
    "index" int8,
    "muni_id" int8,
    "municipal" text,
    "year" int8,
    "activity" text,
    "elec_con_pu" float8,
    "elec_con_mmbtu" float8,
    "elec_exp_dollar" float8,
    "elec_emissions_co2" float8,
    "ng_con_pu" float8,
    "ng_con_mmbtu" float8,
    "ng_exp_dollar" float8,
    "ng_emissions_co2" float8,
    "foil_con_pu" float8,
    "foil_con_mmbtu" float8,
    "foil_exp_dollar" float8,
    "foil_emissions_co2" float8,
    "total_con_mmbtu" float8
);


-- Table Comment
COMMENT ON TABLE "tabular"."mapc-lead-commercial" IS '@name mapcLeadCommercial2';
```

**Comment by benjie** [comment] 2019-11-06 11:51
Hi @mzagaja I think you mistook the second error as being the same as the first; it was not. When I reproduced this the second error was:

```
Error: A type naming conflict has occurred - two entities have tried to define the same type 'MapcLeadIndustrialsOrderBy'.

  The first entity was:

    Adding connection "orderBy" argument for table "tabular"."mapc-lead-industrial". You can rename the table's GraphQL type via:

      COMMENT ON TABLE "tabular"."mapc-lead-industrial" IS E'@name newNameHere';

  The second entity was:

    Adding connection "orderBy" argument for table "tabular"."mapc_lead_industrial". You can rename the table's GraphQL type via:

      COMMENT ON TABLE "tabular"."mapc_lead_industrial" IS E'@name newNameHere';

```

Note this relates to the `mapc-lead-industrial` table, not the `mapc-lead-commercial` table that you originally renamed.

This seems to be a bizarre schema with lots of duplicated tables. I've written a plugin to rename all the tables with dashes in:

```js
module.exports = builder => {
  builder.hook('inflection', inflectors => {
    return {
      ...inflectors,
      _tableName(table) {
        const original = inflectors._tableName.call(this, table);
        if (table.name.includes("-")) {
          return original + 'Dashes';
        }
        return original;
      }
    };
  });
}
```

Put that in a file called `plugin.js` and run PostGraphile as:

```
npx postgraphile -c postgres://postgres@localhost:6432/postgres -s tabular --enhance-graphiql --dynamic-json --append-plugins `pwd`/plugin.js
```

That should get you up and running with that schema.

**Comment by benjie** [comment] 2019-11-06 11:51
[semi-automated message] Thanks for your question; hopefully we're well on the way to helping you solve your issue. This doesn't currently seem to be a bug in the library so I'm going to close the issue, but please feel free to keep requesting help below and if it does turn out to be a bug we can definitely re-open it 👍

You can also ask for help in the #help-and-support channel in [our Discord chat](http://discord.gg/graphile).

**Closed by benjie** 2019-11-06 11:51 UTC
Labels: ✖️ invalid

**Comment by bastianhilton** [comment] 2021-08-08 07:44
i'm having the same issue as the original poster, when running your plugin.js file with my connection string, i get this error message:

ERROR: some of the parameters you passed could not be processed: '/plugin.js'

For help, run `postgraphile --help`

Any help on fixing all the duplicates in my database schemas to get postgraphile to run properly?

**Comment by benjie** [comment] 2021-08-08 09:13
Looks like maybe you used a space instead of a comma? Please share your command line.

**Comment by bastianhilton** [comment] 2021-08-08 09:18
postgraphile -c "postgresql://postgresusername:mypassword@localhost:5432/mydatabase"

PostGraphile v4.12.3 server listening on port 5000 🚀

  ‣ GraphQL API:         http://localhost:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://localhost:5000/graphiql (RECOMMENDATION: add '--enhance-graphiql')
  ‣ Postgres connection: postgres://postgres:[SECRET]@localhost/meeovioscar
  ‣ Postgres schema(s):  public
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Node.js version:     v14.16.1 on win32 x64
  ‣ Join Daniel Woelfel in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

Error: A naming conflict has occurred - two entities have tried to define the same key 'nodeId'.

  The first entity was:

    Default field included in newWithHooks call for 'CmsPage'. Adding table type for table "public"."cms_page". You can rename the table's GraphQL type via a 'Smart Comment':

      COMMENT ON TABLE "public"."cms_page" IS E'@name newNameHere';

  The second entity was:

    Adding field for column "node_id" on table "public"."cms_page". You can rename this field with a 'Smart Comment':

      COMMENT ON COLUMN "public"."cms_page"."node_id" IS E'@name newNameHere';
    at Object.extend (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphile-build\node8plus\extend.js:33:13)
    at PgColumnsPlugin/GraphQLObjectType:fields/PgColumns (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphile-build-pg\node8plus\plugins\PgColumnsPlugin.js:86:12)
    at SchemaBuilder.applyHooks (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphile-build\node8plus\SchemaBuilder.js:264:20)
    at fields (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphile-build\node8plus\makeNewBuild.js:505:40)
    at resolveThunk (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphql\type\definition.js:480:40)
    at defineFieldMap (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphql\type\definition.js:692:18)
    at GraphQLObjectType.getFields (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphql\type\definition.js:633:27)
    at collectReferencedTypes (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphql\type\schema.js:366:81)
    at collectReferencedTypes (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphql\type\schema.js:368:9)
    at collectReferencedTypes (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphql\type\schema.js:368:9)

then I tried this:

npx postgraphile -c "postgresql://postgresusername:mypassword@localhost:5432/mydatabase" -s tabular --enhance-graphiql --dynamic-json --append-plugins `pwd` /plugin.js
ERROR: some of the parameters you passed could not be processed: '/plugin.js'

For help, run `postgraphile --help`

I omitted my connection details but the format is the same.

**Comment by benjie** [comment] 2021-08-08 09:21
Edited your comment to add formatting; you have a space immediately before `/plugin.js`; remove it.

**Comment by bastianhilton** [comment] 2021-08-08 09:35
without the space in the command line it just says Error: Cannot find module '`pwd`/plugin.js'. In my comment before pasting it to github, it only has one space.

**Comment by benjie** [comment] 2021-08-09 08:24
Are you on Windows perchance? Change that whole phrase to be the full path to the plugin. The pwd command on *nix gives you the current working directory, so that plus /plugin.js is the full absolute path to the plugin.

**Comment by bastianhilton** [comment] 2021-08-09 08:35
Yes i'm on windows, i did the command again along with the full path to the file:

npx postgraphile -c "postgresql://postgresusername:mypassword@localhost:5432/mydatabase" -s tabular --enhance-graphiql --dynamic-json --append-plugins `pwd` C:\Users\username\OneDrive\Documents\My Websites\Handmade Sites\Backend-Projects\plugin.js

and it still says Error: some of the parameters you passed could not be processed: C:\\Users\\username\\OneDrive\\Documents\\My Websites\\Handmade Sites\\Backend-Projects\\plugin.js

**Comment by bastianhilton** [comment] 2021-08-09 08:35
I'm on Windows 10 21H1, both on Windows 10 and on my other machine Windows 10 Pro, same message.

**Comment by benjie** [comment] 2021-08-09 09:27
Please remove the `pwd` since you're not on Unix and you've already entered the full path.

```
npx postgraphile -c "postgresql://postgresusername:mypassword@localhost:5432/mydatabase" -s tabular --enhance-graphiql --dynamic-json --append-plugins "C:\Users\username\OneDrive\Documents\My Websites\Handmade Sites\Backend-Projects\plugin.js"
```

**Comment by bastianhilton** [comment] 2021-08-11 11:06
Now i get this message:

Failed to load plugin 'C:\\Users\\username\\OneDrive\\Documents\\My Websites\\Handmade Sites\\Backend-Projects\\plugin.js'
C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\cli.js:287
            throw e;
            ^

Error: Cannot find module 'C'
Require stack:
- C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\cli.js
- C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\cli.js:282:20
    at Array.map (<anonymous>)
    at loadPlugins (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\cli.js:274:18)
    at Object.<anonymous> (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\cli.js:342:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Basti\\AppData\\Roaming\\npm\\node_modules\\postgraphile\\build\\postgraphile\\cli.js',
    'C:\\Users\\Basti\\AppData\\Roaming\\npm\\node_modules\\postgraphile\\cli.js'
  ]
}

**Comment by bastianhilton** [comment] 2021-08-11 11:11
Now I get this message:

Failed to load plugin 'C:\\inetpub\\wwwroot\\plugin.js'
C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\cli.js:287
            throw e;
            ^

Error: Cannot find module 'C'
Require stack:
- C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\cli.js
- C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\cli.js:282:20
    at Array.map (<anonymous>)
    at loadPlugins (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\cli.js:274:18)
    at Object.<anonymous> (C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\cli.js:342:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Basti\\AppData\\Roaming\\npm\\node_modules\\postgraphile\\build\\postgraphile\\cli.js',
    'C:\\Users\\Basti\\AppData\\Roaming\\npm\\node_modules\\postgraphile\\cli.js'
  ]
}

Sorry for being a pain, just really want this to work as this seems to be the barrier for my application to use postgraphile.

**Comment by benjie** [comment] 2021-08-11 17:56
I'll ask on Discord and see if one of the Windows users can give you a hand :+1:

**Comment by benjie** [comment] 2021-08-12 08:03
Oh no! This is a bug in _the design_ of the PostGraphile CLI `--append-plugins` option - it uses `:` as the delimeter for the export within the package... :grimacing: 

I'll see if I can get a fix out.

https://github.com/graphile/postgraphile/blob/e0eeb1a1f768f7c757d36a6fa91045add92f9169/src/postgraphile/cli.ts#L606

**Comment by benjie** [comment] 2021-08-12 08:15
@bastianhilton I don't have Windows to test on at the moment, please can you edit `C:\Users\Basti\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\cli.js` and add the following code block immediately after the line that says `const parts = name.split(':')`? ([Line 279 in 4.12.3](https://unpkg.com/browse/postgraphile@4.12.3/build/postgraphile/cli.js), may differ in other releases.)

```js
    // const parts = name.split(':');
    // 👇👇👇👇👇 Add this
    if (process.platform === 'win32' && parts[0].length === 1 && ['\\', '/'].includes(name[2])) {
      // Assume this is a windows path `C:/path/to/module.js` or `C:\path\to\module.js`
      const driveLetter = parts.shift();
      // Add the drive part back onto the path
      parts[0] = `${driveLetter}:${parts[0]}`;
    }
    // 👆👆👆👆👆 Add this
    // let root;
```

Then try again. Assuming this works I'll ship a release with this fix.

**Comment by psigen** [comment] 2023-07-14 20:59
For anyone that comes across this thread specifically when using a field named `node_id` in their database and gets an error similar to the following:
```
Error: A naming conflict has occurred - two entities have tried to define the same key 'nodeId'.

  The first entity was:

    Default field included in newWithHooks call for 'Foo'. Adding table type for table "foos". You can rename the table's GraphQL type via a 'Smart Comment':

      COMMENT ON TABLE "foos" IS E'@name newNameHere';

  The second entity was:

    Adding field for column "node_id" on table "foos". You can rename this field with a 'Smart Comment':

      COMMENT ON COLUMN "foos"."node_id" IS E'@name newNameHere';
```

This can be caused by a table including a field name that normalizes to match the harded globally-unique identifier `nodeId` automatically added to every table scheme as described here: https://www.graphile.org/postgraphile/node-id/

In my case, renaming my field to something other than `node_id` solved the issue once I realized what was conflicting.
