### ISSUE TITLE
Cannot detect function argument array dimensionality in Postgres... Discussion thread

### ISSUE THREAD

**Issue by chris-guidry** [graphile/postgraphile#580] opened 2017-09-08 19:18 UTC
I am working on a process to download data from a device (roughly 40,000 records at a time), and then upload that data to the database. I'd like to combine the data into an array which would be sent to the database all at once versus calling the database 40K times. Also, I'd like for that array to be as small as possible.

With that goal in mind, I created a Postgres function like this:
```
CREATE OR REPLACE FUNCTION public.widget_process(
  person_id integer,
  widgets decimal(14,3)[][]
)

RETURNS void AS $$
DECLARE
  widget decimal(14,3)[];
BEGIN
  FOREACH widget SLICE 1 IN ARRAY widgets LOOP
    INSERT INTO public.widget(log_date, widget2, widget3, widget4, widget5, person_id)
    SELECT to_timestamp(widget[1]), widget[2], widget[3], widget[4], widget[5], person_id;
  END LOOP;
END;
$$ LANGUAGE plpgsql strict SECURITY DEFINER;
```
The function can be called from the database like this:
```
SELECT public.widget_process(3, array[[1504752278,1,2,3,4], [1504752279,5,6,7,8]]);
```

When I call the mutation from GraphiQL, it will work if the "widgets" parameter is a one dimensional array such as [1504752278,1,2,3,4], but if a multidimensional array is passed (such as the SELECT statement above), the following error occurs: `Float cannot represent non numeric value: 1504752278,1,2,3,4`.

I am wondering if a) it's possible to pass a multidimensional array through PostGraphQL, and b) is there some other approach I should be considering to solve this need?

**Comment by benjie** [comment] 2017-09-08 21:38
Please can you confirm if this happens on both v3 (`postgraphql@latest`) and v4 (`postgraphql@next`)?

Providing a minimal SQL schema that reproduces the issue and the GraphQL query you execute in GraphiQL that produces the error will make it a lot faster for me to debug too 👍

**Comment by chris-guidry** [comment] 2017-09-09 01:53
Hi @benjie,

I am currently running version 3.1.0. For version 4, I would need to setup a new environment since I'm not ready to upgrade.

I believe the issue lies with how the function's input parameter is being interpreted. It seems like it's treating this data type: `decimal(14,3)[]**[]**`, as this: `decimal(14,3)[]`, which would explain why it's expecting Float values within the array rather than arrays containing Float values.

The SQL function was a simplified example of the process. Here is an example schema and mutation that should illustrate what's happening.

Schema:
```
CREATE TABLE public.widget
(
  id serial NOT NULL PRIMARY KEY,
  log_date time with time zone NOT NULL,
  widget2 real NOT NULL,
  widget3 real NOT NULL,
  widget4 real NOT NULL,
  widget5 real NOT NULL,
  person_id integer NOT NULL,
  UNIQUE(log_date, person_id),
  CONSTRAINT widget_person_fk_id FOREIGN KEY (person_id)
      REFERENCES public.person (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);
```
Mutation:
```
mutation WidgetProcess($input: WidgetProcessInput!) {
  widgetProcess(input: $input) {
    clientMutationId
  }
}
```
Query Variables:
```
{
  "input": {
  "personId": 1,
  "widgets": [1504752278,-0.122,0.183,-0.427,0.020,-0.036,0.974]
  } 
}
```

Thanks!

**Comment by benjie** [comment] 2017-09-09 07:54
You should be able to try out v4 locally without breaking your setup by just running:

```
npx postgraphql@next -c postgres://user:pass@host/dbname
```

Npx will download and run postgraphql v4 and then throw it away afterwards.

**Comment by chris-guidry** [comment] 2017-09-09 18:54
I tested in v4 and encountered the same error.

The npx package is very helpful. Thanks for the tip.

**Comment by benjie** [comment] 2017-09-11 07:54
Reproduced with schema:

```sql
CREATE TABLE public.person (id serial NOT NULL PRIMARY KEY);

CREATE TABLE public.widget
(
  id serial NOT NULL PRIMARY KEY,
  log_date time with time zone NOT NULL,
  widget2 real NOT NULL,
  widget3 real NOT NULL,
  widget4 real NOT NULL,
  widget5 real NOT NULL,
  person_id integer NOT NULL,
  UNIQUE(log_date, person_id),
  CONSTRAINT widget_person_fk_id FOREIGN KEY (person_id)
      REFERENCES public.person (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE OR REPLACE FUNCTION public.widget_process(
  person_id integer,
  widgets decimal(14,3)[][]
) RETURNS void AS $$
DECLARE
  widget decimal(14,3)[];
BEGIN
  FOREACH widget SLICE 1 IN ARRAY widgets LOOP
    INSERT INTO public.widget(log_date, widget2, widget3, widget4, widget5, person_id)
    SELECT to_timestamp(widget[1]), widget[2], widget[3], widget[4], widget[5], person_id;
  END LOOP;
END;
$$ LANGUAGE plpgsql strict SECURITY DEFINER;

INSERT INTO person DEFAULT VALUES;
INSERT INTO person DEFAULT VALUES;
INSERT INTO person DEFAULT VALUES;
```

**Comment by benjie** [comment] 2017-09-11 08:10
Interestingly when you inspect it with `psql` you get a single-dimension array too:

```
\df widget_process
                             List of functions
 Schema |      Name      | Result data type | Argument data types |  Type
--------+----------------+------------------+---------------------+--------
 c      | widget_process | void             | widgets numeric[]   | normal
(1 row)
```

**Comment by benjie** [comment] 2017-09-11 08:18
Of course, I totally forgot that Postgres ignores both array sizes and number of dimensions:

> However, the current implementation ignores any supplied array size limits, i.e., the behavior is the same as for arrays of unspecified length.
> 
> The current implementation does not enforce the declared number of dimensions either. Arrays of a particular element type are all considered to be of the same type, regardless of size or number of dimensions. So, declaring the array size or number of dimensions in CREATE TABLE is simply documentation; it does not affect run-time behavior.
> -- https://www.postgresql.org/docs/9.6/static/arrays.html

e.g. if you dump the schema you get:

```sql
CREATE FUNCTION widget_process(person_id integer, widgets numeric[]) RETURNS void
    LANGUAGE plpgsql STRICT SECURITY DEFINER
    AS $$
DECLARE
  widget decimal(14,3)[];
BEGIN
  FOREACH widget SLICE 1 IN ARRAY widgets LOOP
    INSERT INTO public.widget(log_date, widget2, widget3, widget4, widget5, person_id)
    SELECT to_timestamp(widget[1]), widget[2], widget[3], widget[4], widget[5], person_id;
  END LOOP;
END;
$$;
```

Since pg_dump itself cannot tell that you created it as a 2D array PostGraphQL has no chance. Your best bet might be to use JSON input instead?

**Comment by benjie** [comment] 2017-09-11 08:23
I've put failing tests in this branch:

https://github.com/graphile/graphile-build/tree/fix-580

I don't know how to make them pass. Maybe a naming convention for function arguments? e.g. `widgets_2d numeric[][]`? (But something much less likely to cause conflicts.)

**Comment by benjie** [comment] 2017-09-11 08:23
Opening this issue up to discussion - anyone with ideas please contribute!

**Comment by chris-guidry** [comment] 2017-09-11 13:47
@benjie I appreciate your efforts to figure out how to handle dimensional arrays. I had not tried inspecting the function within Postgres, but now I see that the metadata for the function does not include the second dimension of the array so there is no way for PostgraphQL to detect it. I like the idea of adding a suffix to the parameter name that would indicate 2d, 3d, etc. To avoid naming conflicts, maybe something like widgets_pg_2d?

In the meantime, I came up with two alternative approaches. The first was to create a custom type called widget_type which included the fields log_date, widget2, widget3, widget4, widget5. Then the input parameter was set to be: widget_type[]. The upside to this approach is that the code is a little more descriptive, and GraphQL had no problem calling the function. The downside is that each row has to be an object which more than doubled the overall length of the data (compared to the dimensional array). This app is going to run on mobile devices so data size is an important consideration.

The second option, was to send one long array of data to the function, then parse it from there. For now I'm going with this option because it minimizes the data length, the Postgres function is not as hairy as I originally imagined, and the foreach loop is no longer needed:
```
CREATE OR REPLACE FUNCTION public.widget_process(
  person_id integer,
  widgets decimal(14,3)[]
)
RETURNS void AS $$
BEGIN
    INSERT INTO public.widget(log_date, widget2, widget3, widget4, widget5, person_id)
    SELECT to_timestamp(widgets[s.i * 5 + 1]), widgets[s.i * 5 + 2], widgets[s.i * 5 + 3],
           widgets[s.i * 5 + 4], widgets[s.i * 5 + 5], person_id
    FROM generate_series(0,array_length(widgets, 1)/5 - 1) AS s(i);
END;
$$ LANGUAGE plpgsql strict SECURITY DEFINER;
```

**Comment by benjie** [comment] 2018-08-15 19:30
[semi-automated message] We try and keep the open issues to actual issues (bugs, etc); this seems like more of a discussion right now, so I'm closing it but please feel free to keep discussing it below 👍

**Closed by benjie** 2018-08-15 19:30 UTC
Labels: add-to-docs, discussion

**Comment by benjie** [comment] 2018-08-15 19:31
(I'm deeming this a "gotcha" rather than a bug, since it's an issue with the underlying PostgreSQL software.)

**Comment by chilltemp** [comment] 2018-09-06 14:43
What about using Smart Comments to override the detected type.  Something like:
```
comment on column my_schema.my_table.my_column is
  E'@type numeric[][]'
```

1. This could help workaround other/future type detection problems.
2. It's not a naming convention, and thus doesn't require changing existing data structures.

**Comment by benjie** [comment] 2018-09-06 16:36
That's certainly an option, the problem is we use `unnest()` quite a bit and that flattens multi-dimensional arrays. If we wanted to support multi-dimensional arrays we'd have to revise the `unnest` code, which is a significant amount of work. I'd be interested in seeing the results of someone doing a POC of this, but don't expect to get it merged during v4 because it could have some significant consequences.
