### ISSUE TITLE
Troubles retrieving current user when using uuid's type for primary key (id column)

### ISSUE THREAD

**Issue by benbonnet** [graphile/postgraphile#713] opened 2018-03-15 11:18 UTC
I'm submitting a ... 

* [x] question
* [ ] bug report
* [ ] feature request

PostGraphile version: latest

Minimal SQL file that can be loaded into a clean database:

```sql
create function sc.authenticate(email text) returns sc.jwt_token as $$
    declare
      account sc.users;
    BEGIN
      IF EXISTS (select 1 from schema.table where sc.users.email = authenticate.email) THEN
        select a.* into account
        from sc.users as a
        where a.email = $1;
        return ('postgraphql_user_public', account.id)::sc.jwt_token;
      ELSE
        insert into sc.users(email)
        values (authenticate.email)
        returning * into account;
        return ('postgraphql_user_public', account.id)::sc.jwt_token;
      END IF;
    END;
    $$ language plpgsql strict security definer;
```
(This one now works perfectly, thx again)

Here's the values contained to the token :

```
{
  "role": "postgraphql_user_public",
  "user_id": "03196d65-ac00-40fc-a19f-03f16f2694be",
  "iat": 1521112540,
  "exp": 1521198940,
  "aud": "postgraphile",
  "iss": "postgraphile"
}
```

```
CREATE TABLE users (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    firstname text,
    lastname text,
    email text,
    token text,
    refreshtoken text,
    meta jsonb,
    slug text,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT users_email_check CHECK ((email ~* '^.+@.+..+$'::text))
);

CREATE TYPE jwt_token AS (
	role text,
	user_id uuid
);

create function sc.current_user() returns sc.users as $$
      select *
      from sc.users
      where id = current_setting('jwt.claims.user_id')::uuid
    $$ language sql stable;

GRANT ALL ON FUNCTION "current_user"() TO postgraphql_user_public;
GRANT USAGE ON SCHEMA deemx TO postgraphql_user_public;
grant select on table sc.users to postgraphql_user_public;
grant insert, update, delete on table sc.users to postgraphql_user_public;
```

Steps to reproduce:

run the mutation 

```
mutation Authenticate($email: String!) {
  authenticate(input: { email: $email } ) {
     jwtToken
    query {
      currentUser {
        id
      }
    }
  }
}
```

Current behavior:

Integrated via express, triggering the endpoint in mocha tests :

```
const signinQuery = await request(app)
      .post(`/graphql`)
      .send({
        query: Signin,
        variables: userVariables // those are ok, works if I don't ask for the 'nested' query/currentuser
      })
      .set("Accept", "application/json");
```

The jwt is correctly returned, but error on  :

```
{ errors: 
   [ { message: 'invalid input syntax for uuid: "0"',
       locations: [ { line: 20, column: 9 } ],
       path: [ 'authenticate', 'query', 'currentUser' ] } ],
  data: 
   { authenticate: 
      { jwtToken: 'xxx-token-ok-xxx',
        query: [currentUser: null] } } }
```

Expected behavior:

Getting currentUser data. I also tried extracting it to a single currentUser query, same result. 

Thx again a lot for your help

**Comment by benjie** [comment] 2018-03-15 11:28
This is not a fully reproducible example yet. Can you share the JWT payload please (just the values, not the signature - use https://jwt.io/), also the SQL definition for `sc.jwt_token`, and the SQL definition for whatever powers `currentUser`?

**Comment by benbonnet** [comment] 2018-03-15 11:33
ok, added the first two you've requested; but about currentUser, it is provided by postgraphile provide; am I wrong ?

**Comment by benjie** [comment] 2018-03-15 11:39
`currentUser` is not provided by postgraphile. You probably have a helper function like the one here: https://www.graphile.org/postgraphile/postgresql-schema-design/#using-the-authorized-user

**Comment by benjie** [comment] 2018-03-15 11:40
(If you are using that function, it's most likely the `::integer` that's causing the issue, because you want to cast to `::uuid` instead)

**Comment by benbonnet** [comment] 2018-03-15 11:43
my bad you're right; it is correctly casted already

**Comment by benbonnet** [comment] 2018-03-15 11:45
As we're talking, I think it might be due to postgraphile changing underscores to camel case ( it happened to me on a field in another context; changed it by removing the underscore; the problem disappeared); but hard to tell exactly why

**Comment by benjie** [comment] 2018-03-15 12:03
PostGraphile does indeed change underscores to camel-case - this is because convention in PostgreSQL is to use underscores, and convention in GraphQL is to use camel-case, so we bridge the gap for you. It's possible to prevent this by overriding the inflector but I'm afraid I've not surfaced a nice API to do this yet.

**Comment by benjie** [comment] 2018-03-15 12:03
To confirm: is this issue now solved?

**Comment by benbonnet** [comment] 2018-03-15 13:29
ok I had `alter database node set jwt.claims.userid to 0`, so i've tried `alter database node set jwt.claims.userid to 'some-correctly-randomly-formatted-uuid'`

But then I'm just getting null for `currentuser` rather than the error specified

**Comment by benjie** [comment] 2018-03-15 13:37
```sql
      where id = current_setting('jwt.claims.user_id')::uuid
```

^ This would benefit from the `missing_ok` parameter of `current_setting`:

```sql
      where id = current_setting('jwt.claims.user_id', true)::uuid
```

This negates the need for the default setting (which omits the underscore incorrectly).

You're also setting the default userid to `0` which isn't a valid UUID. You should set it to `''` and use `nullif` to ignore it; e.g.


```sql
alter database node set jwt.claims.user_id to '';

create function sc.current_user() returns sc.users as $$
      select *
      from sc.users
      where id = nullif(current_setting('jwt.claims.user_id', true), '')::uuid
    $$ language sql stable;
```

**Comment by benbonnet** [comment] 2018-03-15 13:44
ok thx so much.

I have this working (after having first queried the signin endpoint, retrieved the token, and requerying by passing the token in the header) :

```
const currentUser = `
  query {
    currentuser {
      id
      firstname
      lastname
    }
  }
`;
export default currentUser;
```

But still currentuser is null when using it in the first mutation described here

**Comment by benjie** [comment] 2018-03-15 13:47
Yeah; that's because you're running the query with an anonymous JWT. Your authenticate function needs to re-define the setting to make it take effect, e.g. with `perform set_config('jwt.claims.user_id', user.id)`

**Comment by benbonnet** [comment] 2018-03-15 13:51
ok i see, `perform set_config('jwt.claims.user_id', user.id)`to be added in the signin function somewhere
thx alot

**Comment by benjie** [comment] 2018-03-15 13:59
[semi-automated message] To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.

**Closed by benjie** 2018-03-15 13:59 UTC

**Comment by benbonnet** [comment] 2018-03-15 18:02
@benjie  hard for me to re-open as I think it's due to a lack of knowledge on my side on pg ; so only if you have time to help futher

But for now, by adding i'm getting `'column "jwt.claims.userid" does not exist'`

 ```
... code above
IF EXISTS (select 1 from deemx.users where deemx.users.email = authenticate.email) THEN
        select a.* into account
        from deemx.users as a
        where a.email = $1;
        perform set_config("jwt.claims.userid", account.id);
        return ('postgraphql_user_public', account.id)::deemx.jwt_token;
... code above
```

But I'm just unsure about where to set it, probably not the right position /:

Besides that, what differs from [the example](https://github.com/graphile/postgraphile/blob/master/examples/forum/schema.sql#L172) ? Isn't the `perform` you're mentioning missing ? Saying that, because "sub-querying" (don't know how to call it sorry) as it is provided can't be done without it right ?

**Comment by benjie** [comment] 2018-03-15 18:57
You’ve used double quotes; you need single. Double is for identifiers (tables, columns, schemas, functions); single is for values (mostly strings)

**Comment by benbonnet** [comment] 2018-03-15 21:57
arf did changed it with simple quote, still not getting it

The pg logs show the following :

```
ERROR:  function set_config(unknown, uuid) does not exist at character 8
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT set_config('jwt.claims.userid', (account.id)::uuid)
CONTEXT:  PL/pgSQL function sc.authenticate(text) line 27 at PERFORM
STATEMENT:  
	      with __local_0__ as (
	        select __local_1__.* from "sc"."authenticate"($1) __local_1__
	      )
	      select (__local_0__)::text from __local_0__
```

The thing is, when I run the following within a psql console session :

```
select set_config('jwt.claims.userid', 'fef745a3-7797-4fa2-81aa-b28b00eb3dre', false);
select current_setting('jwt.claims.userid');
```

I get the uuid

**Comment by benjie** [comment] 2018-03-15 23:02
You need to cast the UUID to text for it to work in set_config - functions are strongly typed and it doesn’t support uuid (that’s what the error message means)

set_config(‘jwt.claims.user_id’, user.id::text)
