### ISSUE TITLE
Error: Schema validation error: operation hooks were not added to the following fields: Mutation.createUser

### ISSUE THREAD

**Issue by Knaackee** [graphile/postgraphile#1511] opened 2021-07-22 08:33 UTC
Posted this before, but at the wrong place i guess :) 

I would like to wrap an existing mutation so that i can do something after the insert.
I followed the guide at: [makeWrapResolversPlugin (graphile-utils)](https://www.graphile.org/postgraphile/make-wrap-resolvers-plugin/#method-1-wrapping-individual-resolvers-of-known-fields)

I have a mutation called createUser and i can see and use it in graphiql.

On startup, i get the following error.

> Error: Schema validation error: operation hooks were not added to the following fields: Mutation.createUser

```
makeWrapResolversPlugin({
  Mutation: {
    async createUser(resolve, source, args, context, resolveInfo) {
      await resolve(source, args, context, resolveInfo);
      // do something
    },
  },
}),
```
Why is that?

Thanks!

**Comment by benjie** [comment] 2021-07-22 14:30
Duplicate of https://github.com/graphile/graphile-engine/issues/750

**Closed by benjie** 2021-07-22 14:30 UTC
Labels: 🐛 bug
