### ISSUE TITLE
Filter error in testing query

### ISSUE THREAD

**Issue by libinvarkey** [graphile/postgraphile#1490] opened 2021-05-31 09:08 UTC
[GraphQLError: Unknown argument "filter" on field "Query.dmsPhysicalRwGoalSetting".],

test("allDmsPhysicalRoVwStoreMasters", async () => {
  //const data  = GetDashboardItemsData;
  await RunGraphQLQuery(
    // GraphQL query goes here:
    `query getGoalSettingsByGroupName($group_name: String, $store_id: String) {
      dmsPhysicalRwGoalSetting(filter: { groupName: { equalTo: $group_name },
      storeId: { equalTo: $store_id } }) {
        nodes {
          goalId
          goalName
          goalValue
          storeId
        }
      }
    }
      `,
    // GraphQL variables:
    {
      group_name: "abc",
      store_id: "1234",
    },
    // Additional props to add to `req` (e.g. `user: {session_id: '...'}`)
    {},
    // This function runs all your test assertions:
    async (json) => {
      
      expect(json.errors).toBeFalsy();
      expect(json.data).toBeTruthy();
      expect(json.data.allDmsPhysicalRoVwStoreMasters.totalCount).toBe(2);
      // expect(json.data.currentUser).toMatchObject({
      //     id: user.id,
      // });
    }
  );
});

**Comment by jemgillam** [comment] 2021-05-31 10:06
This is a duplicate of another issue you opened https://github.com/graphile/starter/issues/265

We can't help you debug your code - `Query.dmsPhysicalRwGoalSetting` is not in Starter. You could try talking over your code in our community at https://discord.gg/Graphile or booking a paid call with Benjie at https://benjie.dev

Please use our issue template in the future, this will help us better spot if your issue is in our software or in the code you are writing. You're close to being labelled a spammer and being blocked from opening any new issues.

**Closed by jemgillam** 2021-05-31 10:06 UTC

**Comment by libinvarkey** [comment] 2021-05-31 10:27
ok
