### ISSUE TITLE
GraphQL version conflicts with other libraries

### ISSUE THREAD

**Issue by james-ff** [graphile/postgraphile#772] opened 2018-06-04 17:45 UTC
PostGraphile version: ^4.0.0-beta.10

Steps to reproduce:

- run postgraphile with `"graphql": "^0.13.2"` also in package.json
- 0.13.2 is required by other libraries I am using

Current behavior:

- Console Output:

```
Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/Users/jamesbellamy/Developer/_Repositories/ADEPt/backend/node_modules/postgraphile/node_modules/graphql/jsutils/instanceOf.js:17:13)
 .........
```

Expected behavior:

- Same version, no errors

**Comment by benjie** [comment] 2018-06-04 17:48
Due to bundling GraphiQL we have a dependency on https://github.com/graphql/codemirror-graphql which only supports up to GraphQL 0.12.x. Follow:

https://github.com/graphql/codemirror-graphql/issues/247

**Comment by benjie** [comment] 2018-06-04 17:51
I'm going to close this because there's not much we can do about it right now. 

Duplicate of https://github.com/graphile/postgraphile/issues/720

**Closed by benjie** 2018-06-04 17:51 UTC

**Comment by james-ff** [comment] 2018-06-04 18:14
Ok, Thanks!
