### ISSUE TITLE
Process exits on failed initial schema build even in "library mode"

### ISSUE THREAD

**Issue by AlexGustafsson** [graphile/postgraphile#1042] opened 2019-04-11 15:30 UTC
I'm submitting a ... 

* [x] bug report (of sorts)
* [ ] feature request
* [ ] question 

PostGraphile version: 4.3.3

Steps to reproduce:

```
const express = require('express');
const {postgraphile} = require('postgraphile');

const app = express();

// The IP should NOT have Postgresql listening
const postgraphileMiddleware = postgraphile('127.0.0.1', ...);

app.use(postgraphileMiddleware);
```

Current behavior:

The process exits, regardless of error handling, due to not being able to connect to the host.

```
A fatal error occurred when building the initial schema, so the process will now exit. Error details:

Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
```

This is not especially graceful:

https://github.com/graphile/postgraphile/blob/3ebea166b2099b1d731e50b1f225d7c2f25d8abc/src/postgraphile/postgraphile.ts#L192-L205

Expected behavior:

The process should not be exited. At least not when used as a library. Errors should be escalated and be the chore of the application itself.

**Comment by benjie** [comment] 2019-04-11 15:49
Indeed; this only occurs at startup as a protection against misconfiguration, but the `process.exit(1)` is indeed too harsh and is particularly problematic for people using the software via Docker/Kubernetes. This is on my near-term TODO list.

Closing as duplicate of #1041

**Closed by benjie** 2019-04-11 15:49 UTC

**Comment by benjie** [comment] 2019-04-29 14:35
The new "retry on fail" behaviour introduced in #1044 (v4.4.0-beta.10) is being disabled by default in #1062 (which will be released with v4.4.0-rc.1); instead you must opt into the feature:

**To _not_ exit on init fail you need to set either `--retry-on-init-fail` on the CLI or `retryOnInitFail: true` in the library.**

Sorry for this inconvenience, but I wanted to ensure that 4.4 is not a breaking change for existing users who may be relying on the exit-on-fail behaviour of v4.0-v4.3.

rc1 should (hopefully) be out in the next few hours.

**Comment by jmcudk** [comment] 2019-05-14 23:52
I feel like this fix didn't really deal with the initial issue, in my specific application I want to be able to handle errors and exit gracefully rather than just having postgraphile breaking everything and spewing an extravagant amount of logs, my personal preference would be that instead of logging and calling exit, throwing a specific error that the application can catch and deal with.

**Comment by benjie** [comment] 2019-05-15 04:20
Throwing an error doesn’t really make sense because it would be async so there’s nothing to catch it; but we could call a callback function. What errors are you trying to handle, and how do you plan to handle them, exactly?

**Comment by jmcudk** [comment] 2019-05-16 00:42
Most likely error I'm going to hit is a connection error, and I'd like the ability to (if it can't connect) present that to the user in a way that fits with our applications output (without needing to make some sort of hacky solution)

So as the original poster said "Errors should be escalated and be the chore of the application itself." hence why my thoughts went to throwing an error, cause then I could put the postgraphile middleware in a try catch block within an async function itself, and if it works everything goes smoothly, if it doesn't I can display that to the user appropriately and exit gracefully

also apologies if that's a bit rambley struggling to find the words to convey what i'd like, also want to say that I really enjoy the tool, It's really easy to use :)

**Comment by benjie** [comment] 2019-05-16 11:21
As mentioned, a try/catch block can’t work because the postgraphile middleware call is synchronous but the error happens asynchronously, but it sounds like a callback would achieve your goal.

**Comment by benjie** [comment] 2019-05-16 11:25
https://github.com/graphile/postgraphile/issues/1073

**Comment by jmcudk** [comment] 2019-05-16 11:26
That would possibly work, thanks for the assist
