### ISSUE TITLE
Slow performance when using orderBy

### ISSUE THREAD

**Issue by danielbuechele** [graphile/postgraphile#380] opened 2017-03-02 17:32 UTC
I have table of articles with about 100k rows. When I sort this table using `orderBy: PUBLICATION_DATE_DESC` the response is pretty slow. Without the `orderBy` it's fast.
I started debugging it:
`SELECT * FROM articles ORDER BY publication_date DESC LIMIT 10` is super fast. The query generated by PostGraphQL looks like this and is slow.
```
select to_json(__local_0__) as value from "public"."articles" as __local_0__  order by "publication_date" limit 10;
```
Once I remove `to_json` or the ordering it's fast again. Currently there is no index on the publication_date column. I don't understand what's happening there. A first guess would be, that all rows are converted to json before the LIMIT is applied, but I don't understand how this is related to the `ORDER BY`.

**Comment by benjie** [comment] 2017-03-02 19:57
@danielbuechele Please submit an `explain analyze select...` and durations (run each one 5 times and give the lowest result) for the four queries:

1. `select * from articles limit 10;`
2. `select * from articles order by publication_date desc limit 10;`
3. `select to_json(articles) from articles limit 10;`
4. `select to_json(articles) from articles order by publication_date desc limit 10;`

I suspect the missing index is the issue.

**Comment by danielbuechele** [comment] 2017-03-03 08:49
Really appreciate your help:

1. `select * from articles limit 10;`
```
Limit  (cost=0.00..1.17 rows=10 width=1072) (actual time=0.013..0.022 rows=10 loops=1)
  ->  Seq Scan on articles  (cost=0.00..10259.08 rows=87908 width=1072) (actual time=0.013..0.019 rows=10 loops=1)
Planning time: 0.082 ms
Execution time: 0.063 ms
```

2. `select * from articles order by publication_date desc limit 10`
```
Limit  (cost=12158.74..12158.77 rows=10 width=1072) (actual time=94.997..95.003 rows=10 loops=1)
  ->  Sort  (cost=12158.74..12378.51 rows=87908 width=1072) (actual time=94.996..95.001 rows=10 loops=1)
        Sort Key: publication_date DESC
        Sort Method: top-N heapsort  Memory: 36kB
        ->  Seq Scan on articles  (cost=0.00..10259.08 rows=87908 width=1072) (actual time=0.014..51.099 rows=87908 loops=1)
Planning time: 0.124 ms
Execution time: 95.045 ms
```

3. `select to_json(articles) from articles limit 10;`
```
Limit  (cost=0.00..1.19 rows=10 width=32) (actual time=0.086..0.487 rows=10 loops=1)
  ->  Seq Scan on articles  (cost=0.00..10478.85 rows=87908 width=32) (actual time=0.086..0.483 rows=10 loops=1)
Planning time: 0.060 ms
Execution time: 0.503 ms
```

4. `select to_json(articles) from articles order by publication_date desc limit 10;`
```
Limit  (cost=12378.51..12378.54 rows=10 width=40) (actual time=1692.245..1692.248 rows=10 loops=1)
  ->  Sort  (cost=12378.51..12598.28 rows=87908 width=40) (actual time=1692.243..1692.245 rows=10 loops=1)
        Sort Key: publication_date DESC
        Sort Method: top-N heapsort  Memory: 43kB
        ->  Seq Scan on articles  (cost=0.00..10478.85 rows=87908 width=40) (actual time=0.062..1672.467 rows=87908 loops=1)
Planning time: 0.078 ms
Execution time: 1692.305 ms
```

**Comment by danielbuechele** [comment] 2017-03-03 08:59
Creating an index on publication_date fixed the problem.

**Comment by benjie** [comment] 2017-03-03 09:11
**WOW**; what the hell?! That's an **incredible** difference.

I... I'm way out of my depth on this. I would expect `T_4 = T_2 + (T_3 - T_1)`; i.e. I'd expect the search time and the serialization time to be the two variables; but 1.6 seconds for that last query is... Unexpected.

**Comment by benjie** [comment] 2017-03-03 09:17
Yeah, I've reproduced this locally - I think you're correct in that it's running to_json on everything before filtering.

**Comment by benjie** [comment] 2017-03-03 09:18
Evidence for this: `explain analyze select to_json(articles) from articles;` takes the same amount of time as `explain analyze select to_json(articles) from articles order by publication_date desc limit 10;`

**Comment by calebmer** [comment] 2017-03-05 03:26
Do you think we should only allow you to order on columns that have an index? Or perhaps add a deprecation warning (using GraphQL enum deprecations) to orderings without an index?

**Comment by benjie** [comment] 2017-03-05 14:45
I've been thinking that we should only allow ordering by columns with an indexes for a few weeks now (I keep seeing the ability to order by my JSON fields which is unexpected!); I would definitely support deprecating them now and removing them from the next major version.

One caveat to this is that someone may have a compound index (e.g. `(user_id, thing_id)`) where they want to allow sorting by thing_id and they know that user_id will always be set to one specific value. I think, in this case, we should just take the naïve way out and only allow sorting by columns that have the index on the first field.

Since we're talking about this, it would be nice to also allow sorting by computed values - we may be able to accomplish this at the same time by reflecting over the indexes; however we'd need to have a decent naming convention for them.

**Comment by benjie** [comment] 2017-03-05 14:55
Please continue discussion in #386

**Comment by benjie** [comment] 2017-03-15 21:22
For anyone interested, here's a bunch of performance experiments I did on a table with 839k rows based on my own theories and some put forward by the lovely people in #postgresql on irc.freenode.net (notably `YS` and `average` 🙏 ):

https://gist.github.com/benjie/02df5fdbd7ee8315712fff83007f3cd1

As we can see, if we're not using an index the next best thing is the CTE.

**Comment by benjie** [comment] 2017-03-15 21:33
> YS: Benjie: BTW, the form "SELECT table FROM table" has this comment in PostgreSQL source code: This is a hack for backwards compatibility with PostQUEL-inspired syntax.  The preferred form now is "rel.*".

**Comment by benjie** [comment] 2017-03-15 21:35
(And for anyone wondering what the hell PostQUEL is: https://www.postgresql.org/docs/9.6/static/history.html)

**Comment by danielbuechele** [comment] 2017-03-16 09:28
Using CTE works for me. However I had to modify the syntax a little:
```
with __local_0__ as (
    select * from latest_articles() as a where true offset 0 limit 10
) select to_json(__local_0__) as value from __local_0__;
```
I imagine it shouldn't be to hard to implement CTEs. Or are there any pitfalls? If you point me in the right direction, I can look into creating a PR.

**Comment by benjie** [comment] 2017-03-16 09:39
@danielbuechele If you have a look through #342 you'll see the various places SQL is used to build queries. I think the main ones that would concern you for this are the ones in PgPaginator\*

I'm not sure what the schedule is for #342, I still need to get some time with @calebmer to work on making it merge-able, but I've been using it in production for the last month. It's likely to cause conflicts if you fix master directly (though hopefully your changes should be relatively small so shouldn't be too hard to unpick); you're also welcome to make them against #342 if you want more performance gains 😉

**Comment by benjie** [comment] 2017-03-16 09:40
(search for 'select' to find the relevant queries)

**Comment by danielbuechele** [comment] 2017-03-16 10:26
I wasn't able to build the branch from #342 but I created a PR on master.

**Comment by benjie** [comment] 2017-07-09 21:02
I hope this is fixed in v4.

**Comment by benjie** [comment] 2018-07-21 12:51
I think this is fixed.

[semi-automated message] Hi, there has been no activity in this issue for over 8 weeks so I'm closing it to keep the issues/pull request manageable. If this is still an issue, please re-open with a comment explaining why.

![](https://media.giphy.com/media/RpNA43Cnd38Bi/giphy.gif?response_id=5925dc27fd5ebd80cc843ee9)

**Closed by benjie** 2018-07-21 12:51 UTC
Labels: Fixed in v4
