### ISSUE TITLE
'Error: certificate has expired' as of 2022-01-08, in Building the Initial Schema

### ISSUE THREAD

**Issue by drbobbeaty** [graphile/postgraphile#1569] opened 2022-01-09 11:59 UTC
### Summary

This weekend, some Certificate expired in the chain of sites that are hit and loaded when Postgraphile does it's _Initial Schema_ creation. I noticed this around 2022-01-09T17:00:00-0500 and it is 100% repeatable.

The specifics of the error are:

```bash
A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

Error: certificate has expired
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
```

Earlier in the day, this was working fine - with no changes to the code in the breakage.

### Steps to reproduce

1) Running on MacBook Pro M1Max, macOS `12.1`... Node `v16.13.1`... Postgraphile `4.12.8`. Also, when running on Google Cloud with Docker's `node:latest` base image as the OS and version of Node - I _still_ get the issue. This is then, not related to macOS `12.1` - exclusively.

2) Simply run with Postgraphile as a Library. My case is:

```javascript
  app.use(
    postgraphile(
      'postgres://localhost:5432/',
      'public',
      {
        watchPg: false,
        graphiql: true,
        enhanceGraphiql: true,
        graphqlRoute: '/graphql/v2',
        graphiqlRoute: '/graphiql/v2',
        eventStreamRoute: '/graphql/v2/stream',
        jwtSecret: process.env.JWT_SECRET,
        appendPlugins: [
          require('@graphile-contrib/pg-simplify-inflector'),
          require('postgraphile/plugins').TagsFilePlugin,
        ],
      }
    )
  )
```

And it dies.

3) If I place a function in the `retryOnInitFail:` option, I get the error and the attempt count, and am able to run **_without_** Postgraphile running in the service - but this isn't _ideal_.

### Expected results

That it would run as it has for months now - building the initial schema from the Postgres URL.

### Actual results

Without a `retryOnInitFail:` function, it exits out the Node process - as expected. The error reported is:

```bash
A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

Error: certificate has expired
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
```

### Additional context

Debugging Notes:

* It does not matter what the Postgres Database URL is - even `postgres://localhost:5432` fails (and yes, I have a local Postgresql server running).
* Running GraphiQL doesn't make a difference - `true` or `false` - same error.
* Including the `appendPlugins`, above, or not - makes no difference - same error.
* I looked into the `defaultPlugins` (as leaving out the `appendPlugins` made no difference) to see what, if any calls they were making to any `https://` sites. I found none in the `defaultPlugins` in the Graphiine engine - or in the `pgDefaultPlugins` in that package.
* I cannot find any locations in the Postgraphile code, or it's included Graphile packages where an `https://` resource is loaded in the code - so I can't find a _Smoking Gun_ for the expired Certificate
* There are a lot of dependencies that aren't in the Graphile organization that could be the source of the problem, and I didn't track down each one.

### Possible Solution

I have to run my service _without_ Postgraphile now - as I have no way to update any Certificates.

**Comment by drbobbeaty** [comment] 2022-01-09 12:33
@benjie is there anything I can do to help in the reproduction of this issue? I've got this on a macOS machine, and on a Docker instance in Google Cloud Run... so I know that at least I am able to reproduce it regularly... which is good and bad, I suppose.

**Comment by benjie** [comment] 2022-01-09 12:33
How frustrating! I've attempted to reproduce this, but it works for me:

```
$ npx postgraphile -c postgres:///pggql_test -s a,b,c

PostGraphile v4.12.8 server listening on port 5000 🚀

  ‣ GraphQL API:         http://localhost:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://localhost:5000/graphiql (RECOMMENDATION: add '--enhance-graphiql')
  ‣ Postgres connection: postgres:///pggql_test
  ‣ Postgres schema(s):  a, b, c
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Node.js version:     v16.13.0 on linux x64
  ‣ Join Politics Rewired in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

0 error(s) in 93.76ms :: query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }
```

Could you try running this same command, maybe in a clean folder to rule out other dependencies?

As you note:

> I looked into the defaultPlugins (as leaving out the appendPlugins made no difference) to see what, if any calls they were making to any https:// sites. I found none in the defaultPlugins in the Graphiine engine - or in the pgDefaultPlugins in that package.

we don't make any external requests other than to the PostgreSQL database itself. My first guess was that your PostgreSQL server certificate has expired, but you've already said:

> It does not matter what the Postgres Database URL is - even postgres://localhost:5432 fails (and yes, I have a local Postgresql server running).

so surely it cannot be that.

I'm sorry I have no idea how to help you track this down because I can't think of anything we do that could cause it other than connecting to PostgreSQL itself. It seems that you've tried stripping down to the smallest reproducable example, so all I can do is suggest you go the other direction - build up to a reproduction. Start with a clean folder (no `node_modules` accessible) and run a very simple PostGraphile command line. Assuming that works (which it should) slowly build up to an example closer to what you're doing until you start getting the issue again.

Good luck!

**Comment by benjie** [comment] 2022-01-09 12:40
I've also tried with Docker:

```
$ docker pull graphile/postgraphile
Using default tag: latest
latest: Pulling from graphile/postgraphile
97518928ae5f: Already exists 
468000513d90: Already exists 
7e4d2470b557: Already exists 
26993460ce45: Already exists 
ed312668c76f: Pull complete 
a7a3c6a4b9fe: Pull complete 
01b9a57b6610: Pull complete 
Digest: sha256:4fb0473e789d900ae94af065912d97278b3af67da07233d1476b9dd2cfb62f35
Status: Downloaded newer image for graphile/postgraphile:latest
docker.io/graphile/postgraphile:latest
$ docker run --rm -it --network host graphile/postgraphile -c postgres://test:test@localhost/pggql_test -s a,b,c

PostGraphile v4.12.8 server listening on port 5000 🚀

  ‣ GraphQL API:         http://0.0.0.0:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://0.0.0.0:5000/graphiql (RECOMMENDATION: add '--enhance-graphiql')
  ‣ Postgres connection: postgres://test:[SECRET]@localhost/pggql_test
  ‣ Postgres schema(s):  a, b, c
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Node.js version:     v12.22.7 on linux x64
  ‣ Join Simon Elliott in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

0 error(s) in 110.09ms :: query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }
```

(You've probably noticed in your research, but we even bundle the sponsors into each release rather than making a network request because we don't feel PostGraphile should make any network request you've not told it to.)

**Comment by drbobbeaty** [comment] 2022-01-09 12:44
> 

So I ran:

```bash
$ npx postgraphile -c postgres:///inventory
```

because I didn't have a `pggql_test` database, but I did have a local db called `inventory`, and got:

```bash
$ npx postgraphile -c postgres:///inventory

PostGraphile v4.12.8 server listening on port 5000 🚀

  ‣ GraphQL API:         http://localhost:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://localhost:5000/graphiql (RECOMMENDATION: add '--enhance-graphiql')
  ‣ Postgres connection: postgres:///inventory
  ‣ Postgres schema(s):  public
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Node.js version:     v16.13.1 on darwin arm64
  ‣ Join HR-ON in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

WARNING: there were no matches for makePgSmartTagsPlugin rule 1 - {
  kind: 'attribute',
  match: 'users.password',
  tags: { omit: 'all,many,create,read,update,delete' },
  description: undefined
}
```

Now this is good news, because it didn't crash, so I will have to figure out how to add things back in see what breaks.

I appreciate the help... I'm sorry this wasn't simpler.

**Comment by benjie** [comment] 2022-01-09 14:33
Great start :+1:  Best of luck on your hunt!

[semi-automated message] This doesn't currently seem to be a bug in the library so I'm going to close the issue, but please feel free to keep requesting help below and if it does turn out to be a bug we can definitely re-open it 👍

You can also ask for help in the #help-and-support channel in [our Discord chat](http://discord.gg/graphile).

**Closed by benjie** 2022-01-09 14:33 UTC
Labels: 😓 cannot-reproduce

**Comment by drbobbeaty** [comment] 2022-01-09 17:20
@benjie I have some _interesting_ news. 

One of the dependencies in the `package.json` is:

```javascript
    "pg-connection-string": "^2.0.0",
```

and the current version is `2.5.0`. This is something that I noticed as I was digging in the code a bit.

Interestingly enough, when I configure Postgraphile to run with a simple URL, like:

```bash
$ npm postgraphile -c postgres:///inventory
```

it works just fine. Great!

But when I give it a URL that has my "working" domain, I have to include, in the URL the connection options:

```
postgres://blah.mycompany.app:5677/database?sslmode=require&ssl=1
```

The key there is that if I _omit_ the `sslmode=require` and `ssl=1` from the connection string, it tries to connect without SSL/TLS, and that's no good. Thankfully, that's what `pg-connection-string` is all about!

When I looked at the options of the `pg-connection-string` I noticed:

* `sslmode=no-verify` - sets `ssl` to `{ rejectUnauthorized: false }`

and when I set that, it worked like a charm! Using SSL, but not verifying the Certificate chain.

So... I don't know if the difference in `pg-connection-string` between version `2.0.0` and `2.5.0` is big, but I can say that it _appears_ that there are two possibilities:

1) There is a package computing the expiration date of each Certificate used by `pg-connection-string` or `pg` - that is _miscalculating_ the expiration date of one of the Certs in the chain.

2) There is a Cert in the chain for the service I'm using that is, in fact, expired.

-----

I just wanted to update you on the issue... and what I'm finding so that you can decide what, if any, changes/updates should be made on your end.

**Comment by benjie** [comment] 2022-01-09 17:27
That was honestly my first guess :grin: 

> My first guess was that your PostgreSQL server certificate has expired, but you've already said:
> > It does not matter what the Postgres Database URL is - even postgres://localhost:5432 fails (and yes, I have a local Postgresql server running).

Maybe when you were testing you weren't successfully replacing your local database URL, or you were connecting locally using SSL somehow?

Anyway; glad you got it figured out!

**Comment by drbobbeaty** [comment] 2022-01-09 17:53
@benjie I extracted the data too quickly... :) I reported a false negative.

> It does not matter what the Postgres Database URL is - even postgres://localhost:5432 fails (and yes, I have a local Postgresql server running).

It fails because it didn't see the default database - when I used:

* `postgres://localhost:5432` - **failed** -- couldn't find the default database.
* `postgres:///inventory` - worked
* `postgres://localhost:5432/inventory` - worked

So it came down to the question of the Cert, or the Cert chain being expired, or incorrectly calculating it as _expired_.

-----

Then I pulled down a simple Bash script to run some checks on the domain... and there is got interesting... According to the script:

```bash
# Leaf Certificate Expires In:
	58 days
----
# Leaf Certificate Dates:
Issued  On: Dec  9 00:04:07 2021 GMT
Expires On: Mar  9 00:04:06 2022 GMT
----
```

And there are three Certs in the chain:

```bash
# Certificate Chains:
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = *.libcloud.platter.app
verify return:1
----
```

All seem to verify out. Or so this says... I'm becoming quite suspicious at this point. :) 

So... we might have a Cert expiration - but it's not the Leaf Cert... that's got 58 days left... and then it goes to Let's Encrypt - which _could_ be it - maybe, but that seems hard to believe... again, I am suspicious... 

So I'm digging more.

**Comment by drbobbeaty** [comment] 2022-01-09 17:57
@benjie a co-worker has been able to duplicate the Certificate Expiration with nothing more than `node-postgres`, so we are getting closer.

**Comment by drbobbeaty** [comment] 2022-01-09 18:16
@benjie as we dug into the Let's Encrypt refreshing for the DNS, we found the issue... It was, indeed, expired. I'm very glad, and I'm so very very grateful for all the help, and the clean, nice code you've written - it was easy to follow.

**Comment by benjie** [comment] 2022-01-09 19:30
Fantastic - glad you tracked it down! And thanks for sharing :raised_hands:
