### ISSUE TITLE
Is it possible to specify an inverse function for computed columns?

### ISSUE THREAD

**Issue by saerdnaer** [graphile/postgraphile#746] opened 2018-04-27 12:30 UTC
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version:

We decided to change the database schema for tags on items from a simple text[]  field to to seperate tags table and a items_tags join table. To allow the old queries to work we created a computed column  on the items tables 
```
CREATE OR REPLACE FUNCTION items_tags(i items)
RETURNS text[] as $$
  SELECT ARRAY(SELECT t.text 
  FROM tags t, items_tags at 
  WHERE t.id = it.tag_id AND it.item_id = i.id)
$$ language sql stable; 
```
The computed column works as expected, but is it also possible to make the computed column writable again, aka provide an inverse function? So it possible to extend the generated mutation for item?

Thanks in advance,
Andi

**Comment by benjie** [comment] 2018-04-27 12:38
It should be possible to do this via a plugin, however there are no plugins to do this currently. I definitely want to write one when I get time.

Duplicate of https://github.com/graphile/postgraphile/issues/559

**Closed by benjie** 2018-04-27 12:38 UTC
