### ISSUE TITLE
Id required in mutation when it should not

### ISSUE THREAD

**Issue by jptissot** [graphile/postgraphile#820] opened 2018-07-26 20:28 UTC
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:

using docker-image graphile/postgraphile:latest 

Minimal SQL file that can be loaded into a clean database:

```sql

create table something (
  id bigint generated by default as identity primary key,
  name varchar(64) not null unique,
  description varchar(512) not null,
);
```

Steps to reproduce:

Attempt to run a mutation without supplying the id.

Current behavior:
Mutation requires the id to be passed in instead of figuring out that it is generated
Expected behavior:
Mutation does not require the id to be passed in

**Comment by jptissot** [comment] 2018-07-26 20:31
This is probably related to the new way of writing the PK in postgres 10.

https://blog.2ndquadrant.com/postgresql-10-identity-columns/

**Comment by benjie** [comment] 2018-07-26 20:59
I believe this is a duplicate of #631.

We do not have explicit support for identity columns yet.

**Comment by jptissot** [comment] 2018-07-26 21:01
Makes sense! Thanks for the reply. Feel free to close this

**Closed** 2018-07-26 21:07 UTC
Labels: PG10-compat, duplicate, enhancement
