### ISSUE TITLE
Error: Expected undefined to be a GraphQL nullable type.

### ISSUE THREAD

**Issue by Munksgaard** [graphile/postgraphile#1154] opened 2019-09-11 08:33 UTC
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: 4.4.3

I don't have a minimal SQL script right now, as my schema is rather large (13k lines), and the error only happened when I removed the postgraphile-plugin-nested-mutations plugin as part of a debugging effort on another issue. I just want to record the issue here, and hopefully I'll be able to supply a minimal SQL script later.

Steps to reproduce:

```
DEBUG="graphile-build:warn" npx postgraphile   --connection "$WILLOUGHBY_CONNECTION_STRING"   --schema willoughby
```

Current behavior:

```
PostGraphile v4.4.3 server listening on port 5000 🚀

  ‣ GraphQL API:         http://localhost:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://localhost:5000/graphiql (enhance with '--enhance-graphiql')
  ‣ Postgres connection: postgres://willoughby_postgraphile:[SECRET]@localhost/willoughby
  ‣ Postgres schema(s):  willoughby
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Join Timescale in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

Recoverable error occurred:
  graphile-build:warn Error: Expected undefined to be a GraphQL nullable type.
  graphile-build:warn     at assertNullableType (/home/munksgaard/src/willoughby/node_modules/graphql/type/definition.js:385:11)
  graphile-build:warn     at new GraphQLNonNull (/home/munksgaard/src/willoughby/node_modules/graphql/type/definition.js:345:19)
  graphile-build:warn     at introspectionResultsByKind.class.reduce (/home/munksgaard/src/willoughby/node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:221:23)
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at extend.reduce (/home/munksgaard/src/willoughby/node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:63:109)
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at PgMutationUpdateDeletePlugin.builder.hook (/home/munksgaard/src/willoughby/node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:63:48)
  graphile-build:warn     at SchemaBuilder.applyHooks (/home/munksgaard/src/willoughby/node_modules/graphile-build/node8plus/SchemaBuilder.js:250:20)
  graphile-build:warn     at fields (/home/munksgaard/src/willoughby/node_modules/graphile-build/node8plus/makeNewBuild.js:499:40)
  graphile-build:warn     at resolveThunk (/home/munksgaard/src/willoughby/node_modules/graphql/type/definition.js:438:40) +0ms
```

Expected behavior: No error.

**Comment by Munksgaard** [comment] 2019-09-11 12:56
Here is a minimal SQL that reliably reproduces the problem on my system:

```sql
BEGIN;

CREATE SCHEMA foo;

CREATE TABLE foo.bar (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    idea_id integer NOT NULL,
    user_id integer NOT NULL
);

COMMENT ON COLUMN foo.bar.id IS '@omit create,update';

COMMENT ON COLUMN foo.bar.created_at IS '@omit create,update';

COMMENT ON COLUMN foo.bar.idea_id IS '@omit update';

COMMENT ON COLUMN foo.bar.user_id IS '@omit update';

ALTER TABLE ONLY foo.bar ADD CONSTRAINT bar_pkey PRIMARY KEY (id);

COMMIT;
```

Heres the result of running that schema:

```
$ DEBUG="graphile-build:warn" npx postgraphile --connection "postgres://munksgaard:xyz@localhost/test?ssl=1" --schema foo

PostGraphile v4.4.3 server listening on port 5000 🚀

  ‣ GraphQL API:         http://localhost:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://localhost:5000/graphiql (enhance with '--enhance-graphiql')
  ‣ Postgres connection: postgres://munksgaard:[SECRET]@localhost/test
  ‣ Postgres schema(s):  foo
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Join James Rascoe in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

Recoverable error occurred:
  graphile-build:warn Error: Expected undefined to be a GraphQL nullable type.
  graphile-build:warn     at assertNullableType (/home/munksgaard/src/willoughby/node_modules/graphql/type/definition.js:385:11)
  graphile-build:warn     at new GraphQLNonNull (/home/munksgaard/src/willoughby/node_modules/graphql/type/definition.js:345:19)
  graphile-build:warn     at introspectionResultsByKind.class.reduce (/home/munksgaard/src/willoughby/node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:221:23)
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at extend.reduce (/home/munksgaard/src/willoughby/node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:63:109)
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at PgMutationUpdateDeletePlugin.builder.hook (/home/munksgaard/src/willoughby/node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:63:48)
  graphile-build:warn     at SchemaBuilder.applyHooks (/home/munksgaard/src/willoughby/node_modules/graphile-build/node8plus/SchemaBuilder.js:250:20)
  graphile-build:warn     at fields (/home/munksgaard/src/willoughby/node_modules/graphile-build/node8plus/makeNewBuild.js:499:40)
  graphile-build:warn     at resolveThunk (/home/munksgaard/src/willoughby/node_modules/graphql/type/definition.js:438:40) +0ms
```

**Comment by benjie** [comment] 2019-09-11 16:06
Thank you for the excellent clean reproduction @Munksgaard!

I've tried reproducing this on my machine, but the schema works fine. This leads me to believe that the issue might be because you have multiple versions of `graphql` in your `node_modules` folder.

This is [a common problem](https://twitter.com/Benjie/status/1063145720868454401)

I recommend using "yarn resolutions" to solve it; let me know if you need further instructions.

**Comment by benjie** [comment] 2019-09-11 16:07
By the way, try changing to a completely clean folder on your computer (no `node_modules` in any parent folders) and run the same command again, see if that fixes it.

**Comment by Munksgaard** [comment] 2019-09-11 17:38
> By the way, try changing to a completely clean folder on your computer (no `node_modules` in any parent folders) and run the same command again, see if that fixes it.

Unfortunately, that didn't seem to do the trick. The test project I'm working on is the simple sql file posted above and then I run postgraphile through npx, but there is no package.json or node_modules or anything. Perhaps npx has become confused?

**Comment by benjie** [comment] 2019-09-11 18:36
(Also make sure that `node_modules` doesn't exist in any parent folders, I sometimes find that one's been created by accident.)

Maybe you have a global install of `postgraphile`?

Try using `npx --ignore-existing`

**Comment by benjie** [comment] 2019-09-23 15:23
@Munksgaard Where do we sit on this issue?

**Comment by Munksgaard** [comment] 2019-09-27 17:06
I could reproduce it again using some docker images to ensure that my own system doesn't interfere. Could you try and see if you could reproduce it using the following commands:

```bash
docker run --rm --name test-postgres -e POSTGRES_PASSWORD=mysecret -d -p 5431:5432 postgres

PGPASSWORD=mysecret psql --port 5431 --host localhost --user postgres << EOF
BEGIN;

CREATE SCHEMA foo;

CREATE TABLE foo.bar (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    idea_id integer NOT NULL,
    user_id integer NOT NULL
);

COMMENT ON COLUMN foo.bar.id IS '@omit create,update';

COMMENT ON COLUMN foo.bar.created_at IS '@omit create,update';

COMMENT ON COLUMN foo.bar.idea_id IS '@omit update';

COMMENT ON COLUMN foo.bar.user_id IS '@omit update';

ALTER TABLE ONLY foo.bar ADD CONSTRAINT bar_pkey PRIMARY KEY (id);

COMMIT;
EOF

docker run -it -e DEBUG="graphile-build:warn" graphile/postgraphile --connection postgres://postgres:mysecret@172.17.0.1:5431/postgres --schema foo
```

For the record, this is my output:

```
munksgaard@turing:~/tmp/postgraphile-bug$ docker run --rm --name test-postgres -e POSTGRES_PASSWORD=mysecret -d -p 5431:5432 postgres
3abdb8c81c581e7aff190f01bcf849ac64b43dd6c51a2c92fb3336bcfe7e2b9a
munksgaard@turing:~/tmp/postgraphile-bug$ PGPASSWORD=mysecret psql --port 5431 --host localhost --user postgres << EOF
BEGIN;

CREATE SCHEMA foo;

CREATE TABLE foo.bar (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    idea_id integer NOT NULL,
    user_id integer NOT NULL
);

COMMENT ON COLUMN foo.bar.id IS '@omit create,update';

COMMENT ON COLUMN foo.bar.created_at IS '@omit create,update';

COMMENT ON COLUMN foo.bar.idea_id IS '@omit update';

COMMENT ON COLUMN foo.bar.user_id IS '@omit update';

ALTER TABLE ONLY foo.bar ADD CONSTRAINT bar_pkey PRIMARY KEY (id);

COMMIT;
EOF

BEGIN
CREATE SCHEMA
CREATE TABLE
COMMENT
COMMENT
COMMENT
COMMENT
ALTER TABLE
COMMIT
munksgaard@turing:~/tmp/postgraphile-bug$ docker run -it -e DEBUG="graphile-build:warn" graphile/postgraphile --connection postgres://postgres:mysecret@172.17.0.1:5431/postgres --schema foo

PostGraphile v4.4.4 server listening on port 5000 🚀

  ‣ GraphQL API:         http://0.0.0.0:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://0.0.0.0:5000/graphiql (enhance with '--enhance-graphiql')
  ‣ Postgres connection: postgres://postgres:[SECRET]@172.17.0.1:5431/postgres
  ‣ Postgres schema(s):  foo
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Join Dan Lynch in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

Recoverable error occurred:
  graphile-build:warn Error: Expected undefined to be a GraphQL nullable type.
  graphile-build:warn     at assertNullableType (/postgraphile/node_modules/graphql/type/definition.js:385:11)
  graphile-build:warn     at new GraphQLNonNull (/postgraphile/node_modules/graphql/type/definition.js:345:19)
  graphile-build:warn     at /postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:221:23
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at /postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:63:109
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at /postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:63:48
  graphile-build:warn     at SchemaBuilder.applyHooks (/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:252:20)
  graphile-build:warn     at fields (/postgraphile/node_modules/graphile-build/node8plus/makeNewBuild.js:505:40)
  graphile-build:warn     at resolveThunk (/postgraphile/node_modules/graphql/type/definition.js:438:40) +0ms
```

**Comment by benjie** [comment] 2019-09-30 10:44
I have reproduced it with this script.

**Comment by benjie** [comment] 2019-09-30 10:56
We don't support `@omit update` on all the individual columns; instead you should `@omit update` on the table. This is similar to how `GRANT UPDATE () ON foo.bar TO whomever;` would be a syntax error.

**Comment by benjie** [comment] 2019-09-30 11:00
Fixed in https://github.com/graphile/graphile-engine/pull/531

**Comment by Munksgaard** [comment] 2019-09-30 11:04
Ah yes, that makes sense. Thank you :+1:

**Closed** 2019-09-30 11:44 UTC
