### ISSUE TITLE
postgraphile performance degrades on simple sort with large dataset

### ISSUE THREAD

**Issue by cdaringe** [graphile/postgraphile#933] opened 2018-12-02 04:58 UTC
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: `4.1.0`

# problem

- postgraphile performance degrades on simple sort with large dataset

# current behavior

- with 1M items, a simple sort on an indexed column takes > 13 seconds.

# expected behavior

- performance that matches simpler sql, which returns < 1 second

# demo

- a repeatable example, and step-by-step demo with datas is posted here:

https://github.com/cdaringe/slow-postgraphql-one-million-sort

(sorry, i meant to title the repo as postgraphile, not postgraphql :$, forgive me!)

**Comment by benjie** [comment] 2018-12-02 10:48
Protip: use `DEBUG="graphile-build-pg:sql"` for a much better formatted SQL debugger output!

I'm not getting the query times you are; for me, rather than >13s it comes in at

~ 1.7s for @latest  
~ 4.1s for @next

This shows a performance regression in 4.1; most likely caused by the partial move to JSONB. I'll need to investigate this further before I release 4.1.

I put the JSON stuff in the wrong place, it's being evaluated on each row before the order/limit is applied and for a top-N heapsort that's very expensive as it's effectively being done for every row. The whole point of the CTE here was to avoid this issue and issues like it! Fortunately it's easy to fix; take our original query:

```sql
with __local_1__ as (
  select to_json(
    (
      jsonb_build_object(
        '@node'::text,
        (
          jsonb_build_object(
            'addr1'::text,
            (__local_2__."addr_1"),
            'beds1'::text,
            (__local_2__."beds_1"),
            'city'::text,
            (__local_2__."city"),
            'county'::text,
            (__local_2__."county"),
            'mls'::text,
            (__local_2__."mls"),
            'priceList'::text,
            (__local_2__."price_list"),
            'zip'::text,
            (__local_2__."zip"),
            'zone'::text,
            (__local_2__."zone")
          )
        )
      )
    )
  ) as "@edges"
  from "public"."listings" as __local_2__
  where (TRUE) and (TRUE)
  order by __local_2__."mls" ASC,
  __local_2__."id" DESC
  limit 10
)
select *
from __local_1__
order by (
  row_number( ) over (partition by 1)
) desc;
```

and move the JSON stuff to outside the CTE:

```sql
with __local_1__ as (
  select *
  from "public"."listings" as __local_2__
  where (TRUE) and (TRUE)
  order by __local_2__."mls" ASC,
  __local_2__."id" DESC
  limit 10
)
select
  to_json(
    (
      jsonb_build_object(
        '@node'::text,
        (
          jsonb_build_object(
            'addr1'::text,
            (__local_1__."addr_1"),
            'beds1'::text,
            (__local_1__."beds_1"),
            'city'::text,
            (__local_1__."city"),
            'county'::text,
            (__local_1__."county"),
            'mls'::text,
            (__local_1__."mls"),
            'priceList'::text,
            (__local_1__."price_list"),
            'zip'::text,
            (__local_1__."zip"),
            'zone'::text,
            (__local_1__."zone")
          )
        )
      )
    )
  ) as "@edges"
from __local_1__
order by (
  row_number( ) over (partition by 1)
) desc;
```

Query time via psql goes down from 3900ms to 104ms.

Thanks for bringing this to my attention; I'll try and get this fixed in the next 4.1 RC 👍

**Comment by benjie** [comment] 2018-12-02 15:12
I've fixed the performance regression.

Solving the JSON performance issue for unindexed queries is not as simple as using `select * from table` as I initially thought above because that will break the applications of anyone who is using column-level SELECT grants (e.g. `grant select(id, name) on my_table to my_role;`). That's probably why I didn't do that previously. Just selecting the columns that are requested will also not solve it, since that will break any computed columns they're using. Column-level select grants are a real issue.

Anyway, as you correctly point out PostGraphile does not need to add `id` to the ordering in this case. We normally do it to ensure that the ordering is unique; but you've already used a unique index so PostGraphile should know the ordering is unique. (This also seems to be an issue in the PostgreSQL query planner, since it should be able to make the same determination and figure out that a index scan on `mls` should be sufficient.)

I've added some code to detect unique columns; which means that this example now uses the index and thus is down to 100ms query time. Please consider sponsoring PostGraphile development 🙏

**Comment by benjie** [comment] 2018-12-02 15:31
Fixed in https://github.com/graphile/graphile-engine/pull/361

**Closed by benjie** 2018-12-02 15:31 UTC
Labels: 🐛 bug

**Comment by benjie** [comment] 2018-12-02 17:03
This fix is out in postgraphile@next

**Comment by benjie** [comment] 2018-12-02 19:44
Whoops; only fixed it for ascending order, not descending order. Will push a new release later in the week.

**Comment by cdaringe** [comment] 2018-12-03 02:00
> I've fixed the performance regression.

🔥 

> Please consider sponsoring PostGraphile development 🙏

done. not much, but a start

> not as simple as using select * from table as I initially thought above because that will break the applications of anyone who is using column-level SELECT grants

huh.  bummer.  I assumed PG would gracefully handle that.  if it does, even partially, perhaps the simpler query could be used with conditional post-processing?  not sure if that makes sense, or if that'd even greatly improve perf.

anyway, thanks for the quick response!

**Comment by benjie** [comment] 2018-12-03 11:36
Thanks; all contributions gratefully received!

Sadly PG does not gracefully handle it:

```sql
create table foo(id serial primary key, name text, secret text);
grant select(id, name) on foo to graphile_visitor;
insert into foo (name, secret) values ('A Smith', 'Nunya');

-- Errors as expected
begin; set local role graphile_visitor; select * from foo; rollback;

-- Doesn't error, as expected
begin; set local role graphile_visitor; select id, name from foo; rollback;

-- Sadly errors, even though nothing but id and name "escape"
begin; set local role graphile_visitor; with a as (select * from foo) select id, name from a; rollback;
```

`postgraphile@4.1.0-rc.5` is now out with the missing descending order fix.

**Comment by benjie** [comment] 2018-12-12 08:36
I’ve not come up with a way to solve this for unindexed queries that is not a breaking change and that works for arbitrary databases without requiring significant work yet.

The current solution is to ensure your queries are indexed.

I’m thinking that selecting the PKs and then re-selecting the results after may be the solution, but that only works if a table has a PK; it’s also messier and more complex and could decrease perf for indexed queries so I’m not super keen on it.

If we just select the relevant fields (without JSON) then we still have to execute computed columns up front which could still be very expensive for unindexed queries.

I’m open to ideas.

**Comment by benjie** [comment] 2018-12-12 13:14
This could be a perfect use case for `ctid` though... That wouldn't require PKs/etc. Would be very PostgreSQL specific though...

**Comment by cdaringe** [comment] 2018-12-12 17:09
So the two main inhibitors are column select grants, and computed columns. I'd like to know a little more about why selecting individual columns as discussed in your original proposal breaks computed columns.  Please using introspection we could run a faster version of the query if that constraint straight wasn't detected?

**Comment by benjie** [comment] 2018-12-14 09:46
Computed columns are passed the full table record, e.g.

```sql
select
  id,
  name,
  users_computed_column(users)
from users;
```

If we select just the specified columns, then we can't _later_ call the computed column.

```sql
with up_front as (
  select
    id,
    name,
  from users
)
select
  id,
  name,
  users_computed_column(???)
from up_front
```

I'm not keen to split the query logic based on introspection: it adds to the planning time, and more importantly it also doubles the number of code paths that need testing.

I'm still thinking `ctid` may be a good solution. It will only work on concrete tables (not views, functions, etc), but it may just work.

**Comment by cdaringe** [comment] 2018-12-14 16:38
i suppose i could write a `fn` to exec a simplified version of the query that postgraphile generates then pass it back to postgraphile, but it's somewhat self-defeating to the value proposition of the library.  of course, i suppose i'm taking it to the limits.  thinking out loud.  i don't know, am i taking it to the limits? i do acknowledge that it's an incredibly difficult ask to match PG perf 1:1, especially in _all_ cases.

i'm using "computed columns" in the private example that led to this discussion by using a cte and config passed in PG. i didn't know the postgraphile computed columns api even existed, ha!

IMHO, computed columns _are_ a really nice sugar API, but matching PG perf is vastly more important.  not a little bit, but a lotta bit.  views are easy to make right next to table migrations, and pumping record data into functions that take smaller primitives over full records is easily achievable.

**Comment by benjie** [comment] 2018-12-14 17:52
Yeah, performance is definitely super important to us - and for the most part PostGraphile performance is incredibly good, you normally just have to be a little careful how you write your queries and ensure you add the relevant indexes.

Computed columns are also extremely important for database-driven development; without them you just have a basic CRUD store which is really missing the point of GraphQL and by extension PostGraphile. PostGraphile has very powerful support for PostgreSQL functions for a reason, and many many people use these - breaking them is a no-go. (They're also implemented in a way that gives them really good performance, which is very important and you'd probably lose that if you had to have the functions look up their own records via PK, for example.)

Since performance issues are solved by adding indexes I recently added the `--no-ignore-indexes` option you can enable to try and reduce the likelihood of missing indexes (it removes relations and filters that don't have indexes, but it does not guarantee that an index will be used).

The issue is that for some queries Postgres accumulates the results as it goes and then throws away the ones it doesn't need; when this computation is nontrivial this causes slowness. The solution is to have Postgres know which rows it needs without having to do a table scan (so it doesn't need to perform unnecessary computations), or to perform the computation afterwards (which is what we've discussed above).

I'd love for someone to sponsor further performance work on PostGraphile; I simply don't have time to look at any big fixes any time soon without a significant increase in funding - the majority of PostGraphile users are very happy with its performance.

**Comment by cdaringe** [comment] 2018-12-14 18:47
> you normally just have to be a little careful how you write your queries and ensure you add the relevant indexes

ya. totally.  in this case, i'm essentially talking about a pretty basic query.  `select * from <view> order by <a-maybe-indexed column>`, and we end up observing a significant perf pg divergence here at the 'phile layer.

> very powerful support for PostgreSQL functions for a reason,

i can't thank you enough for pg fn integrations :) 🎉 . very cool design.

> Since performance issues are solved by adding indexes

i wan't to kindly push back on that. this only works in some cases where you can put indexes everywhere and/ or have a non-wide table.  we've also both already proved that the perf is definitely solved by moving that JSON logic _out_ of the top cte.  PG gives me good perf on the 'phile generated queries sans json'ification, even on non-indexed things.

> significant increase in funding ... the majority of PostGraphile users are very happy with its performance.

ya. i hear ya brother.  that makes perfect sense to me.  it's just a bummer that the query is _almost super fast_, and the reason that it's choking on a big dataset is right under our noses, but we can't touch it because it conflicts with another valuable feature.

```sql
with select a,b,c from table_x as x (
   select m,n, some_fn(x.a, x.b, x.c) from table_z
)
```

from your perspective, how expensive is maintaining both code paths? from a purity perspective, i'm with you 100%, but boy, it would be super enabling.  the above pseudo-code-query achieves the equivalent value for me w/out formal postgraphile computed columns. with non-json changes, gets me rocket perf from PG w/ best-in-class gql from postgraphile.

thanks for having this super long thread as we worked thru it, too.

**Comment by benjie** [comment] 2018-12-14 20:59
I wish I could drop support for column-level select privileges. Doing so would simplify things a LOT and make solving this performance issue a lot easier. It's even on the list of things we discourage:

> **Don't use column-based SELECT grants**: column-based grants work well for `INSERT` and `UPDATE` (especially when combined with `--no-ignore-rbac`!), but they don't make sense for `DELETE` and they cause issues when used with `SELECT`... 
>
> -- https://www.graphile.org/postgraphile/requirements/

Sadly a lot of people use it, and their reasons are generally sound. The alternatives (such as splitting tables on permissions boundaries and using one-to-one relations to join them) are not super compelling for them.

---

I'm open to forking the logic as a global flag, I think. E.g. `--no-grant-select-column`, and make this default in v5. It's still a fair bit of work though.

I don't want to dynamically fork; it would be really unexpected if you have a query that takes 700ms and then you add another field to it (which happens to be a computed column) and suddenly it's 50 seconds not because the new field is slow, but because suddenly it uses a different query structure internally. I'd rather not use `ctid` which only works with views, or rely on unique constraints that we cannot guarantee exist (especially on views).

A global flag is best, I think.
