### ISSUE TITLE
Error: Naming conflict when building object. Cannot have two definitions for property ''.

### ISSUE THREAD

**Issue by solidsnack** [graphile/postgraphile#207] opened 2016-11-04 04:11 UTC
I am not sure how to begin debugging this one. The database doesn't contain any relations or columns named `''`, for starters; but there are some funny ones like `abc/xyz`.

**Comment by benjie** [comment] 2016-11-04 09:25
Hi @solidsnack; is the stacktrace available? It looks like that's a utility used throughout the codebase.

https://github.com/calebmer/postgraphql/blob/1da6f51837b9cce897e12d728142235d69885700/src/graphql/utils/buildObject.ts#L44

https://github.com/calebmer/postgraphql/search?utf8=%E2%9C%93&q=buildObject

**Comment by solidsnack** [comment] 2016-11-07 04:37
```
Error: Naming conflict when building object. Cannot have two definitions for property ''.
    at entries.forEach.entry (/usr/lib/node_modules/postgraphql/build/graphql/utils/buildObject.js:40:19)
    at Array.forEach (native)
    at entriess.forEach.entries (/usr/lib/node_modules/postgraphql/build/graphql/utils/buildObject.js:35:41)
    at Array.forEach (native)
    at Object.buildObject (/usr/lib/node_modules/postgraphql/build/graphql/utils/buildObject.js:35:14)
    at createGqlNamedType (/usr/lib/node_modules/postgraphql/build/graphql/schema/getGqlType.js:138:29)
    at createGqlNullableType (/usr/lib/node_modules/postgraphql/build/graphql/schema/getGqlType.js:126:12)
    at createGqlType (/usr/lib/node_modules/postgraphql/build/graphql/schema/getGqlType.js:108:41)
    at getGqlType (/usr/lib/node_modules/postgraphql/build/graphql/schema/getGqlType.js:25:25)
    at createGqlType (/usr/lib/node_modules/postgraphql/build/graphql/schema/getGqlType.js:107:42)
```

**Comment by calebmer** [comment] 2016-11-07 15:03
Can we get a schema the reproduces this? I agree, the error message is pretty opaque. Once we figure out what exactly is happening we’ll try to cleanup the error message :wink:

**Comment by benjie** [comment] 2016-11-07 19:39
I'm no-where near at the familiarity level of postgraphql to determine what's going on here. It'd be better if Node didn't automatically truncate the stack trace to 10 lines - please could you try again with:

`Error.stackTraceLimit = Infinity;`

or running node via `node --stack-trace-limit=1000`

[Source](http://stackoverflow.com/a/10419288/141284)

**Comment by benjie** [comment] 2016-11-07 19:40
Oops, sorry, didn't see Caleb had replied (GitHub caching issue).

**Comment by benjie** [comment] 2018-08-15 16:17
[semi-automated message] Hi, there has been no activity in this issue for over 8 weeks so I'm closing it to keep the issues/pull request manageable. If this is still an issue, please re-open with a comment explaining why.

![](https://media.giphy.com/media/RpNA43Cnd38Bi/giphy.gif?response_id=5925dc27fd5ebd80cc843ee9)

**Comment by benjie** [comment] 2018-08-15 16:18
(Pretty sure this is fixed in v4 BTW.)

**Closed by benjie** 2018-08-15 16:17 UTC
