### ISSUE TITLE
pre-request stored procedures

### ISSUE THREAD

**Issue by rsubr** [graphile/postgraphile#760] opened 2018-05-10 21:52 UTC
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

PostGraphile version:

4.0.0-beta.8

I'm coming from PostgREST and finding Postgraphile and GraphQL really nice to work with. Thanks heaps for this project!

One of the features I'm missing from PostgREST is the "pre-request" option which takes a stored procedure that is executed at the start of every request. It is called after JWT processing and `set role` are completed but before any data is fetched. This feature permits the developer to easily hook into the PostgREST call flow.

Reference: https://postgrest.org/en/v4.4/auth.html#custom-validation
Discussions: https://github.com/PostgREST/postgrest/pull/632 https://github.com/PostgREST/postgrest/issues/631

Can we have a similar function in Postgraphile?

There are several authentication use cases where this will be useful, checking if a user is active, blacklisted JWT, etc.

Another good use case is to securely set the schema `search_path` for multi-tenant applications using Postgres schema layering.

Example schemas in the DB:
- `client1` -- contains tables + data for this client
- `client2` -- contains tables + data for this client
- `base` -- contains all stored procedures and empty tables 
- `public` -- contains pgcrypto, etc functions

Default `search_path` is `base,public`

If JWT contains a claim `clientname: client1`, the pre-request procedure can query the JWT claim and `set_config('search_path', 'client1,base,public', false) `. All data is now fetched from client1 schema.

Thanks!

**Comment by rsubr** [comment] 2018-05-20 08:10
@mlipscombe many thanks! I tested your PR and it works perfectly in my situation. The `pre-request` DB func gets called immediately after `begin`.

However this does not yet fully address the multi-tenancy requirements. The subsequent queries don't use the `search_path` as they are fully qualified with the schema name and they are sent to the `base` schema instead.

The generated SQL query is `from "base"."staff" as __local_1__`. It would be nice to have `from "staff" as __local_1__` without the schema name.

My `base.pre_request` function uses a hard coded `seach_path` for testing:

```sql
CREATE OR REPLACE FUNCTION base.pre_request() RETURNS VOID AS $$
    BEGIN
        PERFORM set_config('search_path', 'client1,base,public', false);
    END;
$$ LANGUAGE plpgsql;
```

I'm starting postgraphile with these flags:

```bash
./scripts/dev -c postgres://dbuser:dbpass@localhost/dbname --schema base --pre-request base.pre_request
```

When I query `{ allStaff { nodes { id } } }`, I get the following in my logs:

```
  postgraphile:request GraphQL query request has begun. +0ms
  postgraphile:request GraphQL query is parsed. +130ms
  postgraphile:request GraphQL query is validated. +119ms
  postgraphile:postgres begin +5ms
  postgraphile:postgres select base.pre_request() +5ms
  postgraphile:postgres with __local_0__ as (
  postgraphile:postgres       select to_json((__local_1__."id")) as "id"
  postgraphile:postgres       from "base"."staff" as __local_1__
  postgraphile:postgres       
  postgraphile:postgres       where (TRUE) and (TRUE)
  postgraphile:postgres       order by __local_1__."id" ASC
  postgraphile:postgres       
  postgraphile:postgres       
  postgraphile:postgres     ), __local_2__ as (select json_agg(to_json(__local_0__)) as data from __local_0__) select coalesce((select __local_2__.data from __local_2__), '[]'::json) as "data"  +36ms
  postgraphile:postgres:error error: permission denied for relation staff
  postgraphile:postgres:error     at Connection.parseE (/home/rsubr/tmp/postgraphile-dab298b58d0f343ce57c0ea015f9a758c3814324/node_modules/pg/lib/connection.js:553:11)
  postgraphile:postgres:error     at Connection.parseMessage (/home/rsubr/tmp/postgraphile-dab298b58d0f343ce57c0ea015f9a758c3814324/node_modules/pg/lib/connection.js:378:19)
  postgraphile:postgres:error     at Socket.<anonymous> (/home/rsubr/tmp/postgraphile-dab298b58d0f343ce57c0ea015f9a758c3814324/node_modules/pg/lib/connection.js:119:22)
  postgraphile:postgres:error     at emitOne (events.js:116:13)
  postgraphile:postgres:error     at Socket.emit (events.js:211:7)
  postgraphile:postgres:error     at addChunk (_stream_readable.js:263:12)
  postgraphile:postgres:error     at readableAddChunk (_stream_readable.js:250:11)
  postgraphile:postgres:error     at Socket.Readable.push (_stream_readable.js:208:10)
  postgraphile:postgres:error     at TCP.onread (net.js:607:20) +8ms
  postgraphile:postgres commit +70ms
  postgraphile:request GraphQL query has been executed. +25ms
  postgraphile:request GraphQL query request finished. +31ms
1 error(s) in 434.94ms :: { allStaff { nodes { id } } }
```

There's a [similar discussion](https://github.com/PostgREST/postgrest/issues/1106) happening in PostgREST land.

Postgraphile and PostgREST are so similar that with a little bit of effort, one can point both applications to the same DB and enjoy automatic GraphQL and REST APIs. This blows my mind! Thanks for all the hard work :-)

**Comment by benjie** [comment] 2018-05-21 06:31
I can’t see us supporting schema switching in that way any time soon, however it’s easy to achieve outside of PG by using a middleware which defers to one of three PostGraphile middlewares depending on some request variable.

**Comment by rsubr** [comment] 2018-05-24 14:05
@benjie Thanks for clarifying. Can we have only the pre-request feature added?

PR [#766](https://github.com/graphile/postgraphile/pull/766/) has optimizations where transactions are not used unless needed.

If a pre-request hook is specified, it is necessary to run the pre-request hook and the main query inside a transaction. Or at the very least, using the same db connection from pgPool. This is to ensure any variables set in pre-request are visible to the main query.

If a transaction is used, then any variables created using `set local` in the pre-request hook will be visible to the main query and disappear automatically once the transaction completes. This is preferred.

If a transaction is not used, then `set local` is scoped within the pre-request function and variables will not be available once the function exits. To pass variables to the main query, pre-request needs to create session scoped variables using `set`. As connections are reused from the pgPool, these variables may leak to later queries and the dev needs to sanitize all variables during start of every request.

This also applies to any variables set in Postgres functions invoked through custom mutations.

Please offer your views on this.

> I can’t see us supporting schema switching in that way any time soon, however it’s easy to achieve outside of PG by using a middleware which defers to one of three PostGraphile middlewares depending on some request variable.

I'm new to the Node ecosystem and need some guidance. If I want to try implement the schema switching by removing the schema name from the query, which part of code should I look at?

Thanks!

**Comment by rsubr** [comment] 2018-05-31 16:00
> For the latter, check out #427 (comment) - if that doesn’t answer your question please expand 

Still trying to understand the Postgraphile code, I'm new to Javascript.

I am trying to figure out the part of the code which is responsible for creating the SQL query. It would be a great help if you could point this out for me.

Thanks for the help :-)

**Comment by benjie** [comment] 2018-05-31 20:00
I think it would be better to run multiple versions of PostGraphile, one for each schema you wish to switch between, rather than changing the generated SQL. Memory usage shouldn't be much larger (certainly nowhere near 3x as big!). The generated SQL is highly complex, and removing the qualified schema names is not something that I would merge to core because it's risky from a security, performance and stability perspective.

---

Assuming you have 3 different schemas called `schema1`, `schema2` and `schema3` you want to switch between them based on a property of the user, you can build 3 different PostGraphile middlewares:

```js
const { postgraphile } = require('postgraphile');

const options = {
  graphiql: true,
};

const connectionString = 'postgres://localhost/my_db';

const services = {
  schema1: postgraphile(connectionString, 'schema1', options),
  schema2: postgraphile(connectionString, 'schema2', options),
  schema3: postgraphile(connectionString, 'schema3', options),
};
```

Then you would use an Express middleware to expose the relevant schema based on some parameter:

```js
const express = require('express');
const app = express();

app.use((req, res, next) => {
  if (req.user.usesSchema1) {
    services.schema1(req, res, next);
  } else if (req.user.usesSchema2) {
    services.schema2(req, res, next);
  } else {
    services.schema3(req, res, next);
  }
});

app.listen(5000);
```

Does that make more sense?

**Comment by rsubr** [comment] 2018-06-01 17:00
I agree that my request should never be a part of core. Any small mistake may expose the entire DB.

Thanks for the detailed explanation :pray: :+1:

**Comment by benjie** [comment] 2018-08-15 22:38
[semi-automated message] To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.

**Closed by benjie** 2018-08-15 22:38 UTC
Labels: enhancement

**Comment by sstubbs** [comment] 2018-10-02 16:33
Hi,

Thank you for this great project.

I have reading through most the issues regarding multi tenant. I too have a system where each company gets their own identical database in terms of schema. I understand why you want to isolate everything into one query via all the plugins for performance as well as security. 

I have tried various solutions for current problem and this is what I have come up with.

So on each request I am checking companies and starting a postraphile middleware via express-dynamic-middleware if not currently available. Then removing these if there is no user from a company within a certain amount of time.

This works well however:

The first problem with this solution is performance as when a company logs in for the first time in the day there will be a delay of currently about 4 seconds for startup which is not a big problem but it is there.

These databases are quite big so on each middleware startup there is a lot of cpu usage and there is a large amount of memory allocated. This will make it hard for me to scale this. Each middleware consumes 400mb fo ram so even with 3 companies online on a single server I need to start altering the defult node js heap size.

Currently I have created a plugin which appends sql to each query which I can read via a connection pooler and route accordingly. 

I understand why the role is stored in the database but for my use I really need to read the jwt value on each request. I have been going through the source and documentation but I can't find a clean way of doing this.

I know you have answered similar questions to this multiple times and I am sorry to ask it again but can you think of a way I could do a plugin rather than forking the project?

**Comment by benjie** [comment] 2018-10-02 18:31
Hi @sstubbs; could you confirm exactly what your PostgreSQL RDBMS looks like? From what you've said at the moment it sounds like you have thousands of databases, and each database has the same schema. Is this accurate? So:

```
PostgreSQL RDBMS
 |
 |___ customer_1_db
 |   |___ users
 |   |___ posts
 |   |___ emails
 |
 |___ customer_2_db
 |   |___ users
 |   |___ posts
 |   |___ emails
 |
 |___ customer_3_db
 |   |___ users
 |   |___ posts
 |   |___ emails
 |
 |___ customer_4_db
     |___ users
     |___ posts
     |___ emails
  
```

(Just checking I fully understand your use case.)

**Comment by sstubbs** [comment] 2018-10-02 19:41
Hi,

Sorry if it wasn't clear. Yes that is correct. There are only 5-10 company databases at a given point in an old system at the moment that I am porting over. However whenever new people signup a new database is created. So in theory there could be a lot more eventually but even now if all ten are online at the same time even if it's just one user from each company 4GB of ram would be needed even before they start doing queries. 

Whereas if I just had one instance that was routing between databases. Theoretically I would just need 400mb overhead for a few databases.

**Comment by benjie** [comment] 2018-10-02 21:00
400MB of RAM seems very high. What version of PostGraphile are you using? RC5 fixes a big memory issue that crept in that affected dynamic GraphQL queries, so if you're using an older version then upgrading to the latest may (partially) fix it.

To avoid the startup cost you can experiment with using `--write-cache` and `--read-cache` if the databases are 100% identical. The OIDs in your various databases likely differ, I don't think that will cause any issues... but I've never considered it before so... Experiment! Good luck!

You probably want to use the `--max-pool-size` option to decrease the number of PG clients that your server uses. `2` might be a good choice. You might be better passing your own PgPool and customising the options.

If all of this doesn't work, report back with your latest status and I'm sure I can come up with some more ideas.

**Comment by sstubbs** [comment] 2018-10-02 22:33
ok well thanks anyway I will do what you suggest and see if I can get the usage down. Ideally I would like to run it this way. I will let you know know as I progress as it will only become an  issue at a later point but just want to have a plan in place for once this is in production.

**Comment by benjie** [comment] 2018-10-03 06:14
Are you able to send me an anonymised version of your schema? I’d like to solve the RAM issue for sure!

**Comment by sstubbs** [comment] 2018-10-03 11:54
That would be fantastic. I've been trying everything with no luck. How should I send it to you?

**Comment by benjie** [comment] 2018-10-03 16:52
Electronic mail it to my github handle at graphile.org

**Comment by benjie** [comment] 2018-10-03 16:53
Also does it use 400MB from startup, or does it take a while to get there? Steps to reproduce appreciated.

**Comment by sstubbs** [comment] 2018-10-09 05:43
Thank you so much for sorting out my issue. By using postraphile as a schema generator rather than a middleware like you suggested it is working exactly how I needed it to.
